Feat/wallet status
Peersyst/near-mobile-wallet pull request #119
Opened 2022-11-03 12:49 UTC by JordiParraCrespo

2022-11-09 15:58 UTC, AgustinMJ requested changes

2022-11-09 15:58 UTC, AgustinMJ commented on src/module/dao/query/useGetDAOBalance.ts
> +    const { index: usedIndex, network, serviceInstance } = useGetServiceInstance(index);
Millor dir-li `useServiceInstance` per no confondre-ho amb una query

2022-11-09 15:58 UTC, AgustinMJ commented on src/module/dao/query/useGetDaoInfo.ts
> +        const api = network === "testnet" ? config.testnetExplorerLink : config.mainnetExplorerLink;
Aquí dona igual per near, però a ckbull ha de ser el mainnetExplorerApi, pel que hem comentat

2022-11-09 15:58 UTC, AgustinMJ commented on src/config/config.declarations.d.ts
> -        testnetExplorerApi: string;
A cbull son necessaris aquests

2022-11-09 15:58 UTC, AgustinMJ commented on src/module/settings/components/core/DeleteData/DeleteData.tsx
> +    const { setState, reset } = useWalletState();
Millor posar aliases `{setState: setWalletState, reset: resetWalleteState}`així evitem confusions

2022-11-09 15:58 UTC, AgustinMJ commented on src/module/token/query/useGetTokens.ts
> +        //TODO: remove as
Si volem aprofitar aquest refactor a ckbull haurem de fer rollback d'aquest hook

2022-11-09 15:58 UTC, AgustinMJ commented on src/module/transaction/query/useGetTransactions.ts
> +        const tsx = (await serviceInstance?.getTransactions()) as FullTransaction[];
El `as FullTransaction[]` s'haurà de borrar després, no?

2022-11-09 15:58 UTC, AgustinMJ commented on src/module/transaction/query/useSendTransaction.ts
> +/* import { WalletStorage } from "module/wallet/WalletStorage"; */
Per què està comentat això?

2022-11-09 15:58 UTC, AgustinMJ commented on src/module/wallet/WalletStorage.ts
> +    secret?: string;
Aquí potser també hem de vigilar quan ho passem a ckbull, ja que el secret no hi era

2022-11-09 15:58 UTC, AgustinMJ commented on src/module/wallet/hook/useServiceInstanceCreation.ts
> -import walletState, { serviceInstancesMap } from "module/wallet/state/WalletState";
Això s'haurà de restaurar per ckbull. De moment no la borrem

2022-11-09 15:58 UTC, AgustinMJ commented on src/module/wallet/utils/createServiceInstance.ts
> +        if (secretKey) {
else if millor

2022-11-09 15:58 UTC, AgustinMJ commented on test/__mocks__/NearSdk/NearSdk.mock.ts
> +export class NearSdkMock extends BaseMock implements NearSdkMockType {
Millor ficar els mètodes del BaseNearSdkMock a la classe NearSdkMock, si no, si volem fer

```ts
const nearSdkMock = new NearSdkMock();
expect(this.getNfts).toHaveBeenCalled()
```

S'agafaran dades d'altres tests, ja que BaseNearSdkMcok es comparteix, per tant, mola que aquests mètodes es defineixin dins de la classe i siguin independents

2022-11-09 15:58 UTC, AgustinMJ commented on test/unit/src/module/transaction/component/display/BaseSendSummary/BaseSendSummary.spec.tsx
> +            <BaseSendSummary amount={1000} fee={"10"} token={""}>
Per què el token ha de ser ""?

2022-11-09 15:58 UTC, AgustinMJ commented on test/unit/src/module/wallet/component/core/AddWalletModal/AddWalletModal.spec.tsx
> +        const state = new WalletStateMock({
Aquest a ckbull ojo

2022-11-09 15:58 UTC, AgustinMJ commented on test/unit/src/module/wallet/component/core/EditWalletModal/EditWalletModal.spec.tsx
> +    afterAll(() => {
No fa falta, el jest ja fa clear quan acaba el test

2022-11-10 12:18 UTC, JordiParraCrespo commented on src/module/dao/query/useGetDAOBalance.ts
> +    const { index: usedIndex, network, serviceInstance } = useGetServiceInstance(index);
Done

2022-11-10 12:20 UTC, JordiParraCrespo commented on src/module/settings/components/core/DeleteData/DeleteData.tsx
> +    const { setState, reset } = useWalletState();
done

2022-11-10 12:21 UTC, JordiParraCrespo commented on src/module/token/query/useGetTokens.ts
> +        //TODO: remove as
Bueno com tmb s'ha de canviar el serviceInstance ho fem a la branch que em vas comentar ahir

2022-11-10 12:26 UTC, JordiParraCrespo commented on src/module/transaction/query/useGetTransactions.ts
> +        const tsx = (await serviceInstance?.getTransactions()) as FullTransaction[];
I ara tmb jaja

2022-11-10 12:27 UTC, JordiParraCrespo commented on src/module/transaction/query/useSendTransaction.ts
> +/* import { WalletStorage } from "module/wallet/WalletStorage"; */
a near no call i si a ckb fico un commment encara qe en ppi hauria de cladre als dos

2022-11-10 12:28 UTC, JordiParraCrespo commented on src/module/wallet/hook/useServiceInstanceCreation.ts
> -import walletState, { serviceInstancesMap } from "module/wallet/state/WalletState";
okeis

2022-11-10 12:31 UTC, JordiParraCrespo commented on src/module/wallet/WalletStorage.ts
> +    secret?: string;
oki fico comment ben vist!

2022-11-10 12:32 UTC, JordiParraCrespo commented on src/module/wallet/utils/createServiceInstance.ts
> +        if (secretKey) {
done

2022-11-10 14:06 UTC, JordiParraCrespo commented on test/unit/src/module/transaction/component/display/BaseSendSummary/BaseSendSummary.spec.tsx
> +            <BaseSendSummary amount={1000} fee={"10"} token={""}>
Bueno pots ser un alter nom, ara li fico =)

2022-11-10 14:09 UTC, JordiParraCrespo commented on test/unit/src/module/wallet/component/core/EditWalletModal/EditWalletModal.spec.tsx
> +    afterAll(() => {
true

2022-11-10 14:09 UTC, JordiParraCrespo commented on test/unit/src/module/wallet/component/core/AddWalletModal/AddWalletModal.spec.tsx
> +        const state = new WalletStateMock({
he ficat comment

2022-11-10 14:18 UTC, JordiParraCrespo commented on test/__mocks__/NearSdk/NearSdk.mock.ts
> +export class NearSdkMock extends BaseMock implements NearSdkMockType {
okeys

2022-11-23 10:59 UTC, AgustinMJ approved these changes

2022-11-23 11:15 UTC, merged