Wallet Card
Peersyst/near-mobile-wallet pull request #162
Opened 2022-12-03 11:03 UTC by JordiParraCrespo

# Wallet Card

## Issues

- closes #103

## Dependencies

- dev, #155

## Changes

- WalletStorage
- Add ServiceInstance Class
- Add WalletController class (to interact with walletstorage and service instance)
- WalletState: change account for names. Now wallets are set in order
- Falta implementar correctament borrar una wallet #161

2022-12-16 10:09 UTC, AgustinMJ requested changes

2022-12-16 10:09 UTC, AgustinMJ commented on src/module/wallet/component/display/Balance/Balance.types.ts
> +export type FullNumber = bigint | number | string;
Aquest type potser estaria millor a common/types.ts

2022-12-16 10:09 UTC, AgustinMJ commented on src/module/sdk/NearSdkService.ts
> +        nearDecimals: number = BASE_NEAR_DECIMALS,
Els decimals haurien d'estar a la config, no? Perquè hauria de ser igual per totes les instances, així no s'han d'anar passant els decimals a un monton de mètodes

2022-12-19 17:01 UTC, JordiParraCrespo commented on src/module/sdk/NearSdkService.ts
> +        nearDecimals: number = BASE_NEAR_DECIMALS,
Bueno en ppi la idea era separar la config del sdk. I la he ficat al constructor per no haberla de passar cda cop, nse..

2022-12-19 17:05 UTC, JordiParraCrespo commented on src/module/wallet/component/display/Balance/Balance.types.ts
> +export type FullNumber = bigint | number | string;
okeys

2022-12-20 10:25 UTC, AgustinMJ requested changes

2022-12-20 10:25 UTC, AgustinMJ commented on src/module/sdk/NearSdkService.ts
> +        nearDecimals: number = BASE_NEAR_DECIMALS,
Sí però això no s'hauria de poder configurar al constructor, no? Vull dir els decimals de una blockchain no és algo que es vagi canviant, jo ho posaria com a variable privada de classe amb el valor de BASE_NEAR_DECIMALS i ja està, com ho veus?

2022-12-20 10:51 UTC, AgustinMJ approved these changes

2022-12-20 17:02 UTC, merged