Add Wallet
Peersyst/near-mobile-wallet pull request #164
Opened 2022-12-05 08:15 UTC by JordiParraCrespo

# Add wallet screen

## Issues

- closes #145

## Dependencies

- dev, #159

## Changes

- Add wallet screen
- Add wallet card
- UseModalMock

2022-12-16 10:28 UTC, AgustinMJ requested changes

2022-12-16 10:28 UTC, AgustinMJ commented on src/module/wallet/component/core/AddWallet/DialogIcon/BaseDialogIcon.tsx
> +export function BaseDialogIcon(props: SvgProps): JSX.Element {
Jo a això li diria BubbleIcon o algo així que BaseDialogIcon és feillo jajaja

2022-12-16 10:28 UTC, AgustinMJ commented on src/module/wallet/component/core/AddWallet/DialogIcon/DialogIcon.tsx
> +export function DialogIcon(): JSX.Element {
A això doncs li podem dir Bubble, així te sentit amb el BubbleIcon i treiem la paraula Icon que sinó sembla un icon generat per la llibreria quan no ho és

2022-12-20 06:53 UTC, JordiParraCrespo commented on src/module/wallet/component/core/AddWallet/DialogIcon/BaseDialogIcon.tsx
> +export function BaseDialogIcon(props: SvgProps): JSX.Element {
done

2022-12-20 06:53 UTC, JordiParraCrespo commented on src/module/wallet/component/core/AddWallet/DialogIcon/DialogIcon.tsx
> +export function DialogIcon(): JSX.Element {
done

2022-12-20 10:26 UTC, AgustinMJ approved these changes

2022-12-20 15:00 UTC, merged