Feat/import accounts
Peersyst/near-mobile-wallet pull request #165
Opened 2022-12-07 17:32 UTC by JordiParraCrespo

# Import accounts

## Issues

- closes #152, #153, #154

## Dependencies

- dev, #164 

## Changes
- PrivateKeyValidator
- AddWalletModal
- EnterWalletMnemonicScreen
- EnterPrivateKeyScreen
- SwitchMnemonicPrivateKeyScreen

2022-12-16 10:43 UTC, AgustinMJ requested changes

2022-12-16 10:43 UTC, AgustinMJ commented on src/locale/locales/es/common.json
> +    "import_success_other": "¡Cuentas importadas correctament!"
correctamente*

2022-12-16 10:43 UTC, AgustinMJ commented on src/module/wallet/hook/useImportWallets.ts
> +                    wallets: [...state.wallets, ...wallets],
Els state.wallets no haurien d'estar inclosos a wallets?

2022-12-16 10:43 UTC, AgustinMJ commented on src/module/wallet/screen/CreateWalletSuccessScreen.tsx
> +        setStorage();
Quedava guay no el timeout? No et mola? Jajaja

2022-12-16 10:43 UTC, AgustinMJ commented on src/module/wallet/screen/EnterPrivateKeyScreen/EnterPrivateKeyScreen.tsx
> +        setPrivateKey(privateKey);
No podia anar aquí el onSubmit? Em sembla que a react 17 no es podia però a react 18 sí, no ho sé, si no ja està bé jeje

2022-12-16 10:43 UTC, AgustinMJ commented on src/module/wallet/utils/WalletController.ts
> +        const imported = !mnemonic || (secureStorage?.mnemonic && mnemonic !== secureStorage?.mnemonic);
Aquesta condició  `mnemonic !== secureStorage?.mnemonic`no es comprova a l'if anterior? Si `mnemonic === secureStorage?.mnemonic` fa return `{ wallets: [] }`

2022-12-20 06:55 UTC, JordiParraCrespo commented on src/locale/locales/es/common.json
> +    "import_success_other": "¡Cuentas importadas correctament!"
done

2022-12-20 06:56 UTC, JordiParraCrespo commented on src/module/wallet/hook/useImportWallets.ts
> +                    wallets: [...state.wallets, ...wallets],
El import retorna les wallets noves només

2022-12-20 07:57 UTC, JordiParraCrespo commented on src/module/wallet/screen/CreateWalletSuccessScreen.tsx
> +        setStorage();
Al final ho he deixa't així que queda super smooth
```
 setTimeout(() => {
            InteractionManager.runAfterInteractions(() => {
                setStorage();
            });
        }, 500);
```

2022-12-20 07:57 UTC, JordiParraCrespo commented on src/module/wallet/screen/EnterPrivateKeyScreen/EnterPrivateKeyScreen.tsx
> +        setPrivateKey(privateKey);
Bueno de moment ho deixem així ho hauriem de probar q abans donava problemes xq està a varios llocs de la app

2022-12-20 07:57 UTC, JordiParraCrespo commented on src/module/wallet/utils/WalletController.ts
> +        const imported = !mnemonic || (secureStorage?.mnemonic && mnemonic !== secureStorage?.mnemonic);
Improved =)

2022-12-20 10:27 UTC, AgustinMJ commented on src/module/wallet/screen/CreateWalletSuccessScreen.tsx
> +        setStorage();
👌🏼

2022-12-20 13:31 UTC, merged