Set Account name
Peersyst/near-mobile-wallet pull request #167
Opened 2022-12-10 15:27 UTC by JordiParraCrespo

# Create Wallet - Set account name

## Issues

- closes #147 

## Dependencies

- dev, #166 

## Changes
- SetWalletNameScreen

2022-12-16 10:58 UTC, AgustinMJ requested changes

2022-12-16 10:58 UTC, AgustinMJ commented on src/module/common/component/display/DotList/DosList.types.ts
> +import { ColProps } from "@peersyst/react-native-components";
El nom del fitxer te un typo

2022-12-16 10:58 UTC, AgustinMJ commented on src/module/common/component/display/ExplanationList/ExplanationList.tsx
> +const ExplanationList = ({ children, allowed }: ExplanationListProps) => {
Potser GuidelinesList o algo així millor, que explanation sona a paràgraf d'explicació

2022-12-16 10:58 UTC, AgustinMJ commented on src/module/sdk/NearSdkService.ts
> +        return NearSDKService.nameIdIsValid(nameId) && !exist;
`!exist && NearSDKService.nameIdIsValid(nameId)` millor així si no existeix ja no s'ha de calcular nameIdIsValid

2022-12-16 10:58 UTC, AgustinMJ commented on src/module/wallet/screen/SetAccountNameScreen/SetAccountNameScreen.tsx
> +                        placeholder="mycooldid"
mycoolid* Entenc jaja

2022-12-16 10:58 UTC, AgustinMJ commented on src/module/wallet/screen/SetAccountNameScreen/SetAccountNameScreen.tsx
> +                <Button fullWidth type="submit" loading={finalLoding}>
Quan el nameIsAvailabel està loading crec que queda millor posar el button disabled en comptes de loading. Així el loading del button és només pel submit

2022-12-20 08:01 UTC, JordiParraCrespo commented on src/module/common/component/display/DotList/DosList.types.ts
> +import { ColProps } from "@peersyst/react-native-components";
Ojo de alcón!

2022-12-20 08:03 UTC, JordiParraCrespo commented on src/module/common/component/display/ExplanationList/ExplanationList.tsx
> +const ExplanationList = ({ children, allowed }: ExplanationListProps) => {
okeyss

2022-12-20 08:04 UTC, JordiParraCrespo commented on src/module/sdk/NearSdkService.ts
> +        return NearSDKService.nameIdIsValid(nameId) && !exist;
bona =)

2022-12-20 08:04 UTC, JordiParraCrespo commented on src/module/wallet/screen/SetAccountNameScreen/SetAccountNameScreen.tsx
> +                        placeholder="mycooldid"
Ojo de alcón 2.0

2022-12-20 08:09 UTC, JordiParraCrespo commented on src/module/wallet/screen/SetAccountNameScreen/SetAccountNameScreen.tsx
> +                <Button fullWidth type="submit" loading={finalLoding}>
Bueno es q aqí el submit no fa res asíncron encara xq falta escollir de qina conta pillarás el balance.
Ho vaig ficar al button xq al `TextField` no quedava bé
![image](https://user-images.githubusercontent.com/52425638/208615784-b39e2761-d514-4bdf-88f5-3bb32d2571de.png)

2022-12-20 10:33 UTC, AgustinMJ commented on src/module/wallet/screen/SetAccountNameScreen/SetAccountNameScreen.tsx
> +                <Button fullWidth type="submit" loading={finalLoding}>
Me parese bien

2022-12-20 10:33 UTC, AgustinMJ approved these changes

2022-12-20 12:08 UTC, merged