Create Wallet - Select funding account
Peersyst/near-mobile-wallet pull request #169
Opened 2022-12-13 15:45 UTC by JordiParraCrespo

# Create Wallet - Select funding account

## Issues

- closes #148 

## Dependencies

- dev, #167 

## Changes
- Update lib: radio button + selector group
- useWalletSelector hook
- walletSelectorGroup
- AccountSelector
- Select funding account screen

2022-12-16 13:03 UTC, AgustinMJ requested changes

2022-12-16 13:03 UTC, AgustinMJ commented on src/module/wallet/hook/useWalletSelector.ts
> +        handleChange,
Te poca importància, no fa falta que ho canviis però per futurs hooks així crec que és més descriptiu retornar un `setWalletIndex` o algo així en comptes de un `handleChange` que no es pot intuir del tot que canvia realment

2022-12-16 13:03 UTC, AgustinMJ commented on test/unit/src/module/wallet/hook/useWalletSelector.spec.ts
> +import useWalletSelector, { UseWalletSelectorParams } from "module/wallet/hook/useWalletSelector";
Aquest hook potser no feia falta testejar-lo si ja es testeja el WalletSelectorGroup sense mockejar-lo👍🏻

2022-12-20 10:58 UTC, JordiParraCrespo commented on src/config/globalStyles.ts
> +            maxWidth: "100%",
Bueno això és el q vem parlar de fixejar i així per no haber de canviar la llibreria

2022-12-20 11:00 UTC, JordiParraCrespo commented on src/module/common/component/input/SelectorGroup/Selector/Selector.tsx
> +import { Selector as CoreSelector, SelectorControllerProps, useMergeDefaultProps } from "@peersyst/react-components-core";
L'havia copiat per debugar... Deleted

2022-12-20 11:00 UTC, JordiParraCrespo commented on src/module/wallet/component/input/WalletSelectorGroup/WalletSelectorGroup.tsx
> +        <ScrollView>
Bueno es q sempre ha de fer scrollview, ja que el num de accounts por ser força gran

2022-12-20 11:01 UTC, JordiParraCrespo commented on src/module/wallet/hook/useWalletSelector.ts
> +        handleChange,
bueno ho canvio q es un moment

2022-12-20 11:05 UTC, JordiParraCrespo commented on test/unit/src/module/wallet/hook/useWalletSelector.spec.ts
> +import useWalletSelector, { UseWalletSelectorParams } from "module/wallet/hook/useWalletSelector";
aqí si q es veritat!

2022-12-20 11:18 UTC, JordiParraCrespo commented on src/config/globalStyles.ts
> +            maxWidth: "100%",
Però si clean no està

2022-12-20 11:27 UTC, AgustinMJ approved these changes

2022-12-20 12:01 UTC, merged