Feat/integrate tx page
Peersyst/near-mobile-wallet pull request #175
Opened 2022-12-23 08:30 UTC by JordiParraCrespo

# Name

## Issues

closes #

## Dependencies

#

## Changes

-

2022-12-23 10:54 UTC, jpeersyst requested changes
Em sembla tota la part del sdk més neta amb el que has fet així que endevant. Tan sols el TOC de la nomenclature endpoint

2022-12-23 10:54 UTC, jpeersyst commented on src/module/sdk/NearApiService/IndexerService.ts
> +    public endPoint: string;
Endpoint no és exactament el que poses aquí. L'endpoint és el que s'executa quan crides a la url completa.
Crec que seria més adequat dir-li o uri o baseUrl o algo per l'estil

2023-01-10 14:46 UTC, AgustinMJ requested changes

2023-01-10 14:46 UTC, AgustinMJ commented on src/module/transaction/component/display/ActionAmount/ActionAmount.tsx
> +    actionKind: ActionKind;
Per què no "kind" o "type"?

2023-01-10 14:46 UTC, AgustinMJ commented on src/module/transaction/component/display/ActionAmount/ActionAmount.tsx
> +    const action = ACTIONS_WITH_ADD.includes(actionKind) ? "add" : "display";
Si l'array només te un element és millor fer ===

2023-01-10 14:46 UTC, AgustinMJ commented on src/module/common/hook/useFormatDate.ts
> +    return formatDate(locale, date, options);
Això hauria de retornar la funció per fer el format millor

2023-01-10 14:46 UTC, AgustinMJ commented on src/module/transaction/component/display/ActionCard/utils/getAmountAndTokenNameFromAction.ts
> +export interface GetAmountAndTokenNameFromAction {
Jo posaria GetAmountAndTokenNameFromActionResult. GetAmountAndTokenNameFromAction seria s'enten més com el type de la funció en sí.

2023-01-10 14:46 UTC, AgustinMJ commented on src/module/transaction/component/display/BaseSendSummary/BaseSendSummary.tsx
> +                                balance={MathOperations.add(amount, fee)}
Ara que ho penso millor, AmountOperations o BalanceOperations, no?

2023-01-10 14:46 UTC, AgustinMJ commented on src/module/transaction/query/useGetActions.ts
> +        } catch (e) {
Crec que no s'hauria de fer catch, perquè si no tirar l'error no surtirà el toast i l'usuari no sabrà que alguna cosa ha fallat, el warning potser no fa falta

2023-01-10 14:46 UTC, AgustinMJ commented on src/module/transaction/component/display/ActionCard/utils/getAmountAndTokenNameFromAction.ts
> +            tokenName: "token",
Això ha de ser sempre "token"? No pot ser que el tokenName sigui un diferent del natiu? O això és una altra acció?

2023-01-11 10:05 UTC, AgustinMJ approved these changes

2023-01-11 10:05 UTC, merged