Stake modal/set amount
Peersyst/near-mobile-wallet pull request #201
Opened 2023-01-12 11:58 UTC by silvap-javier

# Add Stake 1/4 : Set Stake Amount

## Issues

closes #185 

## Dependencies

branch feat/integrate-send-modal

## Changes

-

2023-01-13 08:52 UTC, GuillemGarciaDev requested changes

2023-01-13 08:52 UTC, GuillemGarciaDev commented on src/module/staking/component/core/AddStakeModal/AddStakeModal.tsx
> +const AddStakeModal = createBackdrop(({ onExited, ...rest }: ExposedBackdropProps) => {
Me suena que hay que meterle un height de "90%" al modal. Creo que en los mockups tiene el tamaño fijo

2023-01-13 08:52 UTC, GuillemGarciaDev commented on src/module/staking/screen/SetAmountStakeScreen/SetAmountStakeScreen.tsx
> +        <>
No hacen falta estos empty tags no??

2023-01-13 08:52 UTC, GuillemGarciaDev commented on src/module/staking/screen/SetAmountStakeScreen/SetAmountStakeScreen.tsx
> +                            <Button variant="text" onPress={() => changeToMaxBalance()}>
Puede que sea solo a mí pero creo que no está alineado del todo 🤔 lo pruebo con otro móvil por si acaso

2023-01-13 08:52 UTC, GuillemGarciaDev commented on src/module/staking/component/core/AddStakeModal/AddStakeModal.tsx
> +    const resetSendState = useResetRecoilState(sendState);
Como ves usar un context en vez de un state para guardar el amount del modal ?? 🤔  Tampoco lo veo mal con state

2023-01-13 08:52 UTC, GuillemGarciaDev commented on src/module/common/component/navigation/BottomBar/BottomBar.tsx
> -                onPress={() => handleNavigation(MainBottomScreens.STAKING)}
Si hiciste merge con dev seguro que tienes ya el StakingSlider con el button de "Stake my tokens" para usar el showModal allí 😉

2023-01-15 23:12 UTC, silvap-javier commented on src/module/staking/component/core/AddStakeModal/AddStakeModal.tsx
> +const AddStakeModal = createBackdrop(({ onExited, ...rest }: ExposedBackdropProps) => {
Ya esta en la siguiente Pr corregido los estilos del modal

2023-01-15 23:12 UTC, silvap-javier commented on src/module/staking/screen/SetAmountStakeScreen/SetAmountStakeScreen.tsx
> +        <>
Done

2023-01-15 23:12 UTC, silvap-javier commented on src/module/staking/screen/SetAmountStakeScreen/SetAmountStakeScreen.tsx
> +                            <Button variant="text" onPress={() => changeToMaxBalance()}>
Creo que se ve bien :)

2023-01-15 23:12 UTC, silvap-javier commented on src/module/staking/component/core/AddStakeModal/AddStakeModal.tsx
> +    const resetSendState = useResetRecoilState(sendState);
Lo hablamos con Jordi y tiramos con recoil :)

2023-01-15 23:12 UTC, silvap-javier commented on src/module/common/component/navigation/BottomBar/BottomBar.tsx
> -                onPress={() => handleNavigation(MainBottomScreens.STAKING)}
En la siguiente PR esta correguido

2023-01-16 09:00 UTC, JordiParraCrespo commented on src/module/common/component/navigation/BottomBar/BottomBar.tsx
> -                onPress={() => handleNavigation(MainBottomScreens.STAKING)}
Esto mejor fuera de esta pr... ya lo he canviado yo :P

2023-01-16 09:03 UTC, JordiParraCrespo commented on src/module/staking/screen/SetAmountStakeScreen/SetAmountStakeScreen.tsx
> +                <NEARAmountTextField
Esto mejor si es un component aparte por si luego necessitamos otro amount con esto del `Max`.
Tmb la parte del max se ha de parecer un poco más a los diseños.
![image](https://user-images.githubusercontent.com/52425638/212638673-87b3803e-cca4-4125-96b5-113ad0a46f43.png)
![image](https://user-images.githubusercontent.com/52425638/212638714-f3017cf5-8767-4712-89ad-10418947750b.png)

2023-01-16 09:03 UTC, JordiParraCrespo commented on src/module/staking/screen/SetAmountStakeScreen/SetAmountStakeScreen.tsx
> +                <Col gap={8}>
Este `Col` creo que no es necesario

2023-01-16 09:04 UTC, JordiParraCrespo commented on src/module/staking/screen/SetAmountStakeScreen/SetAmountStakeScreen.tsx
> +                <NEARAmountTextField
Para hacer el componente seguramente tengas q hacer uso del hook `useControlled`. Este hook té permite q el hook se controle desde fuera y tener un estado interno del componente.

2023-01-17 10:50 UTC, JordiParraCrespo commented
ENCARA no es pot fer merge :P

2023-01-18 08:59 UTC, GuillemGarciaDev commented on src/module/staking/screen/BaseSetAmountStakeScreen/BaseSetAmountStakeScreen.tsx
> +    };
Nice per al unstake

2023-01-18 08:59 UTC, GuillemGarciaDev commented on src/module/transaction/component/input/NEARAmountWithMaxTextField/hook/useNEARAmountAvailable.tsx
> +export function useNEARAmountWithMaxTextFieldController({ index, maxAmount }: UseNEARAmountWithMaxTextFieldControllerParams) {
Li deixem aquest nom? O millor canviem el nom de l'arxiu

2023-01-18 10:17 UTC, JordiParraCrespo commented on src/module/transaction/component/input/NEARAmountWithMaxTextField/hook/useNEARAmountAvailable.tsx
> +export function useNEARAmountWithMaxTextFieldController({ index, maxAmount }: UseNEARAmountWithMaxTextFieldControllerParams) {
done

2023-01-19 08:57 UTC, AgustinMJ approved these changes

2023-01-19 08:57 UTC, merged