Stake modal/select validator
Peersyst/near-mobile-wallet pull request #203
Opened 2023-01-15 23:14 UTC by silvap-javier

# Add Stake 2/4: Select Validator

## Issues

closes #187 

## Dependencies

#197 #201 

## Changes

- Second Step select Validator

2023-01-16 09:39 UTC, JordiParraCrespo commented on src/locale/locales/en/common.json
> +    "validator_name_near": "validator-name.near",
Guay no se mhe hubiera ocurrido ponerlo en el locale =)

2023-01-16 09:56 UTC, JordiParraCrespo requested changes
Te dejo algunos cambios :P
Está bastante bien solo quedan algunas cositas. De UI te dejo la captura y las cositas que he visto del código tmb te las he puesto ya. Buena pr la vdad que no era fácil!! 

![image](https://user-images.githubusercontent.com/52425638/212649690-6d544dca-00db-4c4f-862d-a8b863a83063.png)
![image](https://user-images.githubusercontent.com/52425638/212649740-24039e06-5c0b-4f8e-8445-017e3378bcb0.png)

2023-01-16 09:56 UTC, JordiParraCrespo commented on src/module/main/component/layout/MainGradientScreen/MainGradientScreen.tsx
> +            {scrollable ? (
Antes de hacer merge habrá q traer los últimos cambios de la pr de guillem

2023-01-16 09:56 UTC, JordiParraCrespo commented on src/module/staking/component/core/AddStakeModal/AddStakeModal.tsx
>                      <SetAmountStakeScreen />
Ahora haré un componente base que se encargue de esto

2023-01-16 09:56 UTC, JordiParraCrespo commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +    }, [search]);
Aquí mejor `data` como dependencia del useEffect.

2023-01-16 09:56 UTC, JordiParraCrespo commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +    useEffect(() => {
Creo q este effecto no hace falta mira  de únificarlo todo en uno

2023-01-16 09:56 UTC, JordiParraCrespo commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +            const searchReg = new RegExp(search, "i");
Muy guay esto con la `RegEx`

2023-01-16 09:56 UTC, JordiParraCrespo commented on src/module/staking/component/core/StakingListItem/StakingListItem.tsx
> +        <TouchableHighlight activeOpacity={0.6} underlayColor="#DDDDDD" onPress={() => onSelected(validator)}>
El underlayColor igual lo puedes sacer del theme.
```
const { palette } = useTheme();
```

2023-01-16 09:56 UTC, JordiParraCrespo commented on src/module/staking/screen/SelectValidatorScreen/SelectValidatorScreen.tsx
> +            <TextField
Aquí mejor hacer un componente de `StakeValidatorSelect`.

2023-01-16 09:56 UTC, JordiParraCrespo commented on src/module/staking/screen/SelectValidatorScreen/SelectValidatorScreen.tsx
> +    const [, setStakeState] = useRecoilState(stakeRecoilState);
Tienes un util del recoil que te va mejor en este caso. `useSetRecoilState`.

2023-01-16 09:56 UTC, JordiParraCrespo commented on src/module/staking/screen/SelectValidatorScreen/SelectValidatorScreen.tsx
> +            <TextField
Por otro lado como te comenté al probarlo si q veo q no es "immediata" del todo la búsqueda ni tampoco se da feedback al user mientras esta filtrando. Usaria el hook `useTransition` i mientras `isPending` bostraria un spinner o un texto de `loading...` .

2023-01-16 15:16 UTC, silvap-javier commented on src/module/staking/screen/SelectValidatorScreen/SelectValidatorScreen.tsx
> +            <TextField
Done

2023-01-17 08:04 UTC, JordiParraCrespo commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +    useEffect(() => {
Si pero se puede hacer todo en el mismo `useEffect`. No hace falta tener dos efectos. Lo q hay q añadir `data` al array de deps.
```
useEffect(() => {
        startTransition(() => {
            if(data && search===""){
                  setDataList(data);
            }else if (search !== "" && data) {
                const searchReg = new RegExp(search, "i");
                setDataList(data.filter((item) => searchReg.test(item.accountId)));
            }
        });
    }, [search, data]);
```

2023-01-17 08:05 UTC, JordiParraCrespo commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +    useEffect(() => {
Creo q sería algo así

2023-01-17 08:14 UTC, JordiParraCrespo commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +            ListEmptyComponent={isLoading ? data && dataList.length < 1 ? <EmptyListComponent /> : undefined : <EmptyListComponent />}
Aquí la condición se debería hacer más clara i creo q mejor fuera del return. 
```
const showEmptyList = unificar la condición.
....
ListEmptyComponent={showEmptyList ? <EmptyListComponent /> : undefined }
```

2023-01-17 08:15 UTC, JordiParraCrespo commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +    const { isLoading, data } = useGetAllValidators(index);
Esto en realidad se debería passar por fuera del componente ahora q me fijo. Xq puede ser q haya:
- `useGetAllValidators`
- `useGetCurrentValidators`

2023-01-17 08:16 UTC, JordiParraCrespo commented on src/module/staking/component/core/StakingListItem/StakingListItem.tsx
> +const StakingListItem = ({ validator, onSelected }: StakingListItemProps): JSX.Element => {
StakingListItemSelect

2023-01-17 08:21 UTC, JordiParraCrespo commented on src/module/staking/component/input/StakeValidatorSelect/StakeValidatorSelect.tsx
> +        <>
Faltaria añadir un context para que sirva para los dos tipos de validadores. 
Acabalo de mirar pero el contexto tendría que llevar algo como:
- La accountId
- I el onSelected
- La lista de validadores

2023-01-17 08:24 UTC, JordiParraCrespo commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +const StakingList = ({ search = "", onSelected }: StakingListProps): JSX.Element => {
Tmb que consuma el contexto i no se le tengan que passar props

2023-01-17 08:24 UTC, JordiParraCrespo commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +        startTransition(() => {
Bien el `startTransition`

2023-01-17 08:34 UTC, JordiParraCrespo commented on src/module/staking/component/input/StakeValidatorSelect/StakeValidatorSelect.tsx
> +            <Typography variant="body2Strong">{translate("or_select_a_validator")}</Typography>
Creo q ya lo había comentado lo del `Label`

2023-01-17 11:44 UTC, silvap-javier commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +const StakingList = ({ search = "", onSelected }: StakingListProps): JSX.Element => {
Done

2023-01-17 11:44 UTC, silvap-javier commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +    const { isLoading, data } = useGetAllValidators(index);
Done

2023-01-17 11:44 UTC, silvap-javier commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +    useEffect(() => {
Done

2023-01-17 11:44 UTC, silvap-javier commented on src/module/staking/component/core/StakingList/StakingList.tsx
> +            ListEmptyComponent={isLoading ? data && dataList.length < 1 ? <EmptyListComponent /> : undefined : <EmptyListComponent />}
DONE

2023-01-17 11:44 UTC, silvap-javier commented on src/module/staking/component/core/StakingListItem/StakingListItem.tsx
> +const StakingListItem = ({ validator, onSelected }: StakingListItemProps): JSX.Element => {
Done

2023-01-17 11:44 UTC, silvap-javier commented on src/module/staking/component/input/StakeValidatorSelect/StakeValidatorSelect.tsx
> +        <>
Done

2023-01-17 11:44 UTC, silvap-javier commented on src/module/staking/component/input/StakeValidatorSelect/StakeValidatorSelect.tsx
> +            <Typography variant="body2Strong">{translate("or_select_a_validator")}</Typography>
DOne

2023-01-20 08:11 UTC, merged