Current Validators
Peersyst/near-mobile-wallet pull request #204
Opened 2023-01-16 08:10 UTC by GuillemGarciaDev

# Current Validators

## Issues

closes #182 

## Dependencies

#198 

## Changes

- ValidatorsInformation
- StakingTabs
- useGetStakingValidators
- StakingCurrentValidators

2023-01-16 13:13 UTC, JordiParraCrespo commented on src/module/staking/component/display/StakingCurrentValidators/StakingCurrentValidators.tsx
> +        <StakingCurrentValidatorsRoot>
Aquí fer servir el component de `MainList`

2023-01-16 13:13 UTC, JordiParraCrespo commented on src/module/staking/component/display/StakingCurrentValidators/StakingCurrentValidators.tsx
> +                        You are not staking with any validators
El locale

2023-01-16 13:13 UTC, JordiParraCrespo commented on src/module/staking/component/navigation/StakingTabs/StakingTabs.tsx
> +        {
Cool

2023-01-16 13:13 UTC, JordiParraCrespo commented on src/module/staking/hook/useGetStakingValidators.ts
> +import { Validator } from "module/sdk";
*peersyst-near-sdk

2023-01-16 13:14 UTC, JordiParraCrespo commented on src/module/staking/hook/useGetStakingValidators.ts
> +        if (allValidators) return allValidators.filter(({ accountId }) => accountId === validatorAccountId).length > 0;
això a un `useMemo` o millor a dins del sdk no?

2023-01-16 13:15 UTC, JordiParraCrespo commented on src/module/staking/query/useGetAllValidators.ts
> +        return await serviceInstance.getAllValidators();
Si no hi ha `serviceInstance` que no estigui enabled.

2023-01-16 13:15 UTC, JordiParraCrespo commented on src/module/staking/query/useGetCurrentValidators.ts
> +        return await serviceInstance.getCurrentValidators();
Lo del enabled

2023-01-16 13:15 UTC, JordiParraCrespo commented on src/module/staking/screen/StakingScreen/StakingScreenContent/StakingScreenContent.tsx
> +            <MainStakingCard>
Això crec q va fora

2023-01-16 13:16 UTC, JordiParraCrespo commented on src/module/staking/component/display/StakingCurrentValidators/StakingCurrentValidators.styles.ts
> +    paddingHorizontal: 20,
Aquí millor que el `paddingHorizontal` se li doni desde fora amb la `MainList`

2023-01-16 13:30 UTC, JordiParraCrespo requested changes

2023-01-16 13:30 UTC, JordiParraCrespo commented on src/module/staking/component/core/ValidatorInformation/ValidatorInformation.tsx
> +                    <Account address={accountId} variant="body3Strong" />
Aquí crec q pot arribat a fer overlflow el text

2023-01-16 13:30 UTC, JordiParraCrespo commented on src/module/staking/component/core/ValidatorInformation/ValidatorInformation.tsx
> +                <ActionIcon actionKind="VALIDATOR" />
Tens un enum `TransactionActionKind` per les actions

2023-01-16 13:30 UTC, JordiParraCrespo commented on src/module/staking/component/core/ValidatorInformation/ValidatorInformation.styles.ts
> +    color: status === "active" ? theme.palette.blue : theme.palette.red,
pots fer theme.palette[status === "active" ? "blue" : "status.error"]; o algo així

2023-01-16 13:30 UTC, JordiParraCrespo commented on src/module/staking/component/core/ValidatorInformation/ValidatorInformation.tsx
> +                    <Row>
La `Row` nose si cal

2023-01-16 13:30 UTC, JordiParraCrespo commented on src/module/staking/component/core/ValidatorInformation/ValidatorInformation.tsx
> +            <Col>
Pots fer servir el componetn de `Label`

2023-01-16 15:21 UTC, GuillemGarciaDev commented on src/module/staking/screen/StakingScreen/StakingScreenContent/StakingScreenContent.tsx
> +            <MainStakingCard>
Yes! però depen de la branch anterior

2023-01-18 11:09 UTC, JordiParraCrespo commented on src/module/staking/component/core/ValidatorInformation/ValidatorInformation.styles.ts
> +    color: status === "active" ? theme.palette.blue : theme.palette.red,
done

2023-01-18 12:21 UTC, JordiParraCrespo commented on src/module/staking/component/display/StakingCurrentValidators/StakingCurrentValidators.tsx
> +    const { stakingValidators: validators, isLoading } = useGetStakingValidators();
Aquí fa falta el refetch

2023-01-18 13:26 UTC, JordiParraCrespo commented on src/module/staking/query/useGetAllValidators.ts
> +    });
Falta el enabled. Tmb millor no passarli l'index com a param i q sempre faci la request desde la primera wallet.

2023-01-18 14:53 UTC, merged