Stake modal/confirm stake
Peersyst/near-mobile-wallet pull request #207
Opened 2023-01-17 15:44 UTC by silvap-javier

# Add Stake 3/3: Confirm Stake

## Issues

closes #189 

## Dependencies

#203 

## Changes

- Add step confirmation Modal

2023-01-18 14:43 UTC, JordiParraCrespo commented on src/module/staking/screen/ConfirmStakingScreen/ConfirmStakingScreen.tsx
> +const ConfirmStakingScreen = () => {
Debería ser reusable para el `Unstake`

2023-01-18 14:48 UTC, JordiParraCrespo requested changes

2023-01-18 14:48 UTC, JordiParraCrespo commented on src/module/staking/screen/ConfirmStakingScreen/ConfirmStakingScreen.tsx
> +                        <Button variant="text" fullWidth onPress={() => hideModal(AddStakeModal.id)}>
Aquí tmb un callback para q sea reuable. `onCancel` o algo así.

2023-01-18 14:48 UTC, JordiParraCrespo commented on src/module/staking/screen/ConfirmStakingScreen/ConfirmStakingScreen.tsx
> +                                onPressAction={() => setTab(AddStakeScreens.SELECT_VALIDATOR)}
`onEditValidator`

2023-01-18 14:48 UTC, JordiParraCrespo commented on src/module/staking/screen/ConfirmStakingScreen/ConfirmStakingScreen.tsx
> +                            showFee={false}
Bien x el showFee

2023-01-18 14:48 UTC, JordiParraCrespo commented on src/module/staking/state/StakeState.ts
> +    validator: StakingValidator;
Aquí el dto usa el `Validator` que lo canvié

2023-01-18 14:48 UTC, JordiParraCrespo commented on test/unit/src/module/staking/screen/ConfirmStakingScreen.spec.tsx
> +        //expect(screen.getByText(stakeStateMock.validator.accountId)).toBeDefined();
iepa los commentarios :P

2023-01-18 14:48 UTC, JordiParraCrespo commented on test/__mocks__/common/staking/validator.mock.ts
> +export class ValidatorMock extends BaseMock implements ValidatorMockInterface {
Bien el validator mock

2023-01-18 14:51 UTC, JordiParraCrespo requested changes

2023-01-18 14:51 UTC, JordiParraCrespo commented on src/module/transaction/screen/SendConfirmationScreen/SendConfirmationScreen.tsx
> +        hideModal(SendModal.id);
Ojo el copy and paste del `SendModal`. Lo has de adaptar al stake. Tmb debería ir a la screen de success no cerrar el modal.

2023-01-19 08:55 UTC, silvap-javier commented on src/module/staking/screen/ConfirmStakingScreen/ConfirmStakingScreen.tsx
> +                        <Button variant="text" fullWidth onPress={() => hideModal(AddStakeModal.id)}>
DONE

2023-01-19 08:55 UTC, silvap-javier commented on src/module/staking/screen/ConfirmStakingScreen/ConfirmStakingScreen.tsx
> +                                onPressAction={() => setTab(AddStakeScreens.SELECT_VALIDATOR)}
Done

2023-01-19 08:55 UTC, silvap-javier commented on src/module/staking/screen/ConfirmStakingScreen/ConfirmStakingScreen.tsx
> +                            showFee={false}
:)

2023-01-19 08:55 UTC, silvap-javier commented on src/module/staking/state/StakeState.ts
> +    validator: StakingValidator;
Done

2023-01-19 08:55 UTC, silvap-javier commented on test/unit/src/module/staking/screen/ConfirmStakingScreen.spec.tsx
> +        //expect(screen.getByText(stakeStateMock.validator.accountId)).toBeDefined();
DOne

2023-01-19 08:55 UTC, silvap-javier commented on test/__mocks__/common/staking/validator.mock.ts
> +export class ValidatorMock extends BaseMock implements ValidatorMockInterface {
Doine

2023-01-19 10:56 UTC, closed without merging