Withdraw 1/3: Select Validator
Peersyst/near-mobile-wallet pull request #242
Opened 2023-01-23 11:02 UTC by GuillemGarciaDev

# Withdraw 1/3: Select Validator

## Issues

closes #220 

## Dependencies

#233 

## Changes

- ValidatorInformation (new prop balanceType to indicate which stakingBalance is showing)
- useGetWithdrawValidators (hook to get all current validators that have available balance)
- WithdrawSelectValidatorScreen (component)
- common + tests

2023-01-23 12:59 UTC, JordiParraCrespo requested changes

2023-01-23 12:59 UTC, JordiParraCrespo commented on src/module/staking/component/core/UnstakeModal/UnstakeModal.tsx
> +const UnstakeModal = createBackdrop(({ ...rest }: ExposedBackdropProps): JSX.Element => {
Això es xq faltava com el blur de darrera? Super

2023-01-23 12:59 UTC, JordiParraCrespo commented on src/module/staking/component/input/StakeValidatorSelect/StakeValidatorSelect.tsx
> +    balanceType: keyof StakingBalance;
Aquí faria un extends de les props de `ValidatorStakingBalance`

2023-01-23 12:59 UTC, JordiParraCrespo commented on src/module/staking/hook/useGetStakingDetailsSections.ts
>      const {
Olé!!!

2023-01-23 12:59 UTC, JordiParraCrespo commented on src/module/staking/hook/useGetWithdrawValidators.ts
> +    if (stakingValidators) {
això ha d'anar a dinds de un useMemo i que tingui com a dependencia `stakingValidators`

2023-01-23 12:59 UTC, JordiParraCrespo commented on src/module/staking/hook/useGetWithdrawValidators.ts
> +    const { stakingValidators, isLoading } = useGetStakingValidators();
`stakingValidators = [] `

2023-01-23 12:59 UTC, JordiParraCrespo commented on src/module/staking/hook/useGetWithdrawValidators.ts
> +    return { validators: [], isLoading };
```
const availableValidators = useMemo(() => {
return stakingValidators.filter(({ stakingBalance }) => stakingBalance!.available !== "0");
}, [availableValidators]);
```

2023-01-23 12:59 UTC, JordiParraCrespo commented on src/module/staking/hook/useGetWithdrawValidators.ts
> +    if (stakingValidators) {
Jo faria que retornes tota la resposta del `useQuery` pero q data sigui el resultat del `useMemo`.

2023-01-23 12:59 UTC, JordiParraCrespo commented on test/unit/src/module/staking/screen/SelectValidatorScreen/WithdrawSelectValidatorScreen/WithdrawSelectValidatorScreen.spec.tsx
> +        const mockUseGetWithdrawValidators = jest
Aquí hauries de mockejar el get de tots els validators better amb el canvi q et proposava abans

2023-01-23 13:19 UTC, GuillemGarciaDev commented on src/module/staking/component/core/UnstakeModal/UnstakeModal.tsx
> +const UnstakeModal = createBackdrop(({ ...rest }: ExposedBackdropProps): JSX.Element => {
Yess

2023-01-23 13:33 UTC, JordiParraCrespo requested changes

2023-01-23 13:33 UTC, JordiParraCrespo commented on src/module/staking/hook/useGetStakingDetailsSections.ts
> +            action: "unstake",
Això només hauria de sortir si l'amount es major q zero tens utils al sdk

2023-01-23 13:33 UTC, JordiParraCrespo commented on src/module/staking/hook/useGetStakingDetailsSections.ts
> +            onAction: () => showModal(WithdrawModal),
Idem x aqí s'ha de mirar lamount

2023-01-23 13:33 UTC, GuillemGarciaDev commented on src/module/staking/component/input/StakeValidatorSelect/ValidatorListSelect/ValidatorListSelect.tsx
> +    balanceType: keyof StakingBalance;
done

2023-01-24 12:03 UTC, GuillemGarciaDev commented on src/module/staking/hook/useGetWithdrawValidators.ts
> +    if (stakingValidators) {
@JordiParraCrespo la cosa esque `useGetStakingValidators` fa crides a `getCurrentValidators` i `getAllValidators`, aleshores no se si renta tornar tota la crida dels dos `useQuery`

2023-01-26 10:29 UTC, merged