Fix Balance formatting
Peersyst/near-mobile-wallet pull request #248
Opened 2023-01-24 18:40 UTC by GuillemGarciaDev

# Fix Balance formatting

## Issues

closes #195 

## Changes

- treatNearDecimals (new utils that contains functions to check if balance is below our minimum threshold)
- useFormatNumber

## Notes

This is a first version to make "smarter" our Balance component. All upgrades are welcome!! 🙌🏻

2023-01-26 10:45 UTC, AdriaCarrera requested changes

2023-01-26 10:45 UTC, AdriaCarrera commented on src/module/wallet/utils/treatNearDecimals.ts
> +    const separator = balance.toString().indexOf(".");
El "." depen del locale i en alguns casos pot ser ","
La funció toString() de javascript treu resultats diferents en funció del locale que estiguis:
Sistema espanyol: 1.000,0002
Sistema anglès: 1,000.0002

2023-01-26 10:45 UTC, AdriaCarrera commented on src/module/wallet/component/display/Balance/hook/useFormatBalance.ts
> +    const checkedBalance = balanceBelowMinimum(unsignedBalance) ? NEAR_LIMIT_DECIMAL : unsignedBalance;
Hauriem de tractar el numero com un enter absolut. Llavors agafar la part decimal com un enter i comprovar que sigui major que X

Exemple:
Convertir el numero en enter absolut 123.000000100 = 123000000100
Treure la part entera 123000000100 -> 000000100
Mirar que la part decimal sigui major que el numero minim de decimals que volem cobrir

2023-01-31 08:05 UTC, GuillemGarciaDev commented on src/module/wallet/utils/treatNearDecimals.ts
> +    const separator = balance.toString().indexOf(".");
He estat provant de veure si el toString() modifica el number segons el locale, però no em funciona així 🤔 
No obstant, he observat que independentment del locale sempre arriba el número formatejat de la següent manera:
part_entera.part_decimal
Per tant, no caldría modificar el `separator` segons el locale

2023-02-03 08:24 UTC, AdriaCarrera commented on src/module/common/hook/useFormatNumber.ts
> +        const [integer, decimal] = n.toString().split(".");
Crec que pot ser que la funció n.toString() retorni 0.1 o 0,1 depenent del locale que es trobi. Hauriem de validar si és un o l'altre

2023-02-03 08:31 UTC, AdriaCarrera requested changes

2023-02-03 08:31 UTC, AdriaCarrera commented on src/module/wallet/component/display/Balance/hook/useFormatBalance.ts
> +    const unsignedBalance = stringifiedBalance.replace(/-|,/g, "");
Aquí també hauriem de comprovar que els decimals no s'escriuen amb un punt segons el locale

2023-02-03 08:50 UTC, merged