Refactor - Create/Import Wallet
Peersyst/near-mobile-wallet pull request #260
Opened 2023-01-31 08:05 UTC by JordiParraCrespo

# Refactor - Create/Import Wallet

## Issues

closes #179

## Dependencies

#dev

## Changes

- Create Wallet with the `SendTransactionModal`
- New wallet is created with same privateKey

2023-02-01 09:48 UTC, silvap-javier requested changes
Buenisiiiiima PR , me gusto como sacaste como hook la parte del create

2023-02-01 09:48 UTC, silvap-javier commented on src/module/wallet/component/core/AddWalletModal/AddWalletModal.tsx
> +        <AddWalletModalRoot style={{ height: "100%" }} onExited={handleExited} {...rest}>
style={{ height: "100%" }} ? Esto no podria ir en el style-componente de AddWalletModalRoot

2023-02-01 09:48 UTC, silvap-javier commented on src/module/wallet/component/core/CreateWalletModal/CreateWalletModal.tsx
> +                    index !== 0 && index !== 4
Esto queda un poco complicado para entender, lo podemos meter en una const

2023-02-01 09:48 UTC, silvap-javier commented on src/module/wallet/component/core/ImportWalletModal/hook/useImportWalletModal.ts
> +            }, IMPORT_WALLET_TOAST_DELAY);
bien usada esa constante :)

2023-02-01 09:48 UTC, silvap-javier commented on src/module/wallet/screen/CreateAccountConfirmScreen/CreateAccountConfirmationScreen.tsx
> +        <SendTransactionModal isSuccess={false} isLoading={loading} isError={false} sendTransaction={handleSubmit}>
isError={false} 
isSuccess={false}

esta bien este hardcode?

2023-02-01 09:48 UTC, silvap-javier commented on src/module/wallet/screen/SetAccountNameScreen/SetAccountNameScreen.tsx
>                          placeholder="mycoolid"
Falta transalate al placeholder

2023-02-02 10:12 UTC, JordiParraCrespo commented on src/module/wallet/component/core/AddWalletModal/AddWalletModal.tsx
> +        <AddWalletModalRoot style={{ height: "100%" }} onExited={handleExited} {...rest}>
Bien visto!

2023-02-02 10:13 UTC, JordiParraCrespo commented on src/module/wallet/component/core/CreateWalletModal/CreateWalletModal.tsx
> +                    index !== 0 && index !== 4
total!

2023-02-02 10:13 UTC, JordiParraCrespo commented on src/module/wallet/screen/CreateAccountConfirmScreen/CreateAccountConfirmationScreen.tsx
> +        <SendTransactionModal isSuccess={false} isLoading={loading} isError={false} sendTransaction={handleSubmit}>
Sip! Se handlea de manera distinta

2023-02-02 10:15 UTC, JordiParraCrespo commented on src/module/wallet/screen/SetAccountNameScreen/SetAccountNameScreen.tsx
>                          placeholder="mycoolid"
okeys

2023-02-02 10:59 UTC, silvap-javier approved these changes

2023-02-02 11:00 UTC, merged