Fix - Send + Small fixes
Peersyst/near-mobile-wallet pull request #264
Opened 2023-02-09 15:21 UTC by JordiParraCrespo

# Fix - Send + Small fixes

## Issues

- closes #262 
- closes #253 

## Dependencies

- dev

## Changes

- Add pooling to queries.
- Fix walletcontroller: private key formating and service instance order
- Add waiting time before invalidating the queries when sending/addingstake/creating a name/etc need in order to make some time for the indexer to index the new txs.
- Small fixes

2023-02-10 07:47 UTC, AgustinMJ requested changes
Hauria estat bé dividir-ho en 2 prs diferents

2023-02-10 07:47 UTC, AgustinMJ commented on src/config/config.base.json
> +    "approveTxWaitTime": 3,
Això hauria d'estar en ms, no? Així estan tots els temps en la mateixa unitat

2023-02-10 07:47 UTC, AgustinMJ commented on src/locale/locales/en/common.json
> +    "advise3_text": "When you change your phone you will have to re-import your mnemonics to access your accounts. No one from Near Mobile Wallet or NEAR will ever ask you for your private keys or mn
Bon canvi jajaja

2023-02-10 07:47 UTC, AgustinMJ commented on src/module/common/component/input/Button/Button.styles.ts
> -            paddingHorizontal: 16,
Per què se li treu el padding als botons sm?

2023-02-10 07:47 UTC, AgustinMJ commented on src/module/common/hook/useFormatNumber.ts
> +        const decimalSeparator = translate("number", { val: 1.1 }).slice(1, 2);
Això no ho acabo d'entendre🤔 En teoria ho pot fer el i18n amb el Intl

2023-02-10 07:47 UTC, AgustinMJ commented on src/module/sdk/utils/BalanceOperations.ts
> +            if (returnBN) return res;
Hauria de retornar sempre un Big Number o un string, fer-ho així crec que és bastant confús, jo retornaria sempre el nombre de nears normal

2023-02-10 07:47 UTC, AgustinMJ commented on src/module/token/component/display/TokenIcon/hooks/useGetSupportedTokenImageSource.ts
> +export function getSupportedTokenUri(symbol: string): string | undefined {
Si aquestes dos funcions s'utilitzen a altres llocs jo les ficaria a una carpet utils, si no estan pensades per ser utilitzades a un altre lloc millor no les exportem

2023-02-13 18:09 UTC, JordiParraCrespo commented on src/module/sdk/utils/BalanceOperations.ts
> +            if (returnBN) return res;
Done

2023-02-13 18:13 UTC, JordiParraCrespo commented on src/module/common/hook/useFormatNumber.ts
> +        const decimalSeparator = translate("number", { val: 1.1 }).slice(1, 2);
Fico un comment es per el cas que hi ha 4.0000 o així que surti només 4.
Ja que en alguns casos s'especifica el nombre de decimals anteriorment i això fa que el i18next els mostri encara que siguin zero.

2023-02-13 18:13 UTC, JordiParraCrespo commented on src/module/token/component/display/TokenIcon/hooks/useGetSupportedTokenImageSource.ts
> +export function getSupportedTokenUri(symbol: string): string | undefined {
okey doncs no exportamos :)

2023-02-14 07:08 UTC, AgustinMJ approved these changes

2023-02-14 08:54 UTC, merged