[TA-1000] NearMobile: Bottom bar scan button
Peersyst/near-mobile-wallet pull request #320
Opened 2023-08-09 15:39 UTC by GuillemGarciaDev

# [TA-1000] NearMobile: Bottom bar scan button

## Task

- [[TA-1000] NearMobile: Bottom bar scan button](https://www.notion.so/NearMobile-Bottom-bar-scan-button-1410e8242e6140d49fd04061f2270571?pvs=4)

## Changes

- `BottomBar` with QRCode button and dApps tab
- new `MainBottomBarItem` component (circle component in the middle of the BottomBar)
- New icons (Laptop & QRCode)
- new Button variant `contrast`
- `useThemeMode` hook util
- Stack updated with new routes
- testing updated for `BottomBar` and `MainBottomBarItem` components

2023-08-14 10:18 UTC, JordiParraCrespo requested changes
Bona feina!! Mola el feauture flag aixi podem anar treient cosetes mentres!!

2023-08-14 10:18 UTC, JordiParraCrespo commented on src/module/common/component/input/Button/Button.styles.ts
> +            contrast: {
Aquesta variant la utilitzes?

2023-08-14 10:18 UTC, JordiParraCrespo commented on test/unit/src/module/common/component/navigation/BottomBar/BottomBar.spec.tsx
> +    test("Navigates to Dapps Screen", () => {
Aquí si fas servir el hook de `useConfig` i després el `useCOnfigMock` pots mockejar els feature flags

2023-08-15 14:58 UTC, GuillemGarciaDev commented on src/config/config.declarations.d.ts
> +        signerFeature: boolean;
Em mola molt la idea! Podriem migrar-ho a altres projectes on hi hagi una config una mica dispersa

2023-08-15 15:05 UTC, GuillemGarciaDev commented on src/config/config.declarations.d.ts
> +        signerFeature: boolean;
Ho faig en una PR apart

2023-08-15 15:06 UTC, GuillemGarciaDev commented on src/module/common/component/input/Button/Button.styles.ts
> +            contrast: {
Yes! Per al `MainBottomBarItem`

2023-08-16 10:13 UTC, JordiParraCrespo approved these changes

2023-08-17 14:21 UTC, merged