[TA-1002] NearMobile: Connected sites list
Peersyst/near-mobile-wallet pull request #323
Opened 2023-08-14 14:56 UTC by GuillemGarciaDev

# [TA-1002] NearMobile: Connected sites list

## Tasks

- [[TA-1002] NearMobile: Connected sites list](https://www.notion.so/NearMobile-Connected-sites-list-c8a274dc4021491bb6ee543777d8cc11?pvs=4)

## Dependencies

#321 

## Changes

- `ConnectedSites` settings item to list all connected sites
- `ConnectedSitesModal`
- `Actionable` component
- `ActionableConnectedSitesList` component
- `ConnectedSite` component used in list
- `NearSDKService` updated to fetch account access keys
- testing + locale updates

2023-08-21 07:02 UTC, AgustinMJ requested changes

2023-08-21 07:02 UTC, AgustinMJ commented on src/module/wallet/hook/useParseConnectedSites.ts
> +            .map((accessKey: AccessKeyInfoView) => {
Ojo que això és bastant ineficient, recorrem l'array dos vegades amb el `map` i el `filter`. Amb un `reduce` podem fer les dos coses ala vegada i recorrer l'array un cop

2023-08-21 07:02 UTC, AgustinMJ commented on src/module/wallet/component/feedback/ActionableConnectedSite/ActionableConnectedSite.tsx
> +    const handleAction = () => undefined;
Potser a les coses que no estàn implementades podem ficar un `Alert.alert` i ficar que s'ha d'implementar així hi ha més feedback si algú ho prova. What do u think?

2023-08-22 13:01 UTC, GuillemGarciaDev commented on src/module/settings/components/core/ConnectedSites/ConnectedSites.tsx
> +    return <SettingsMenuItem text={translate("connectedSites")} onPress={() => showModal(ConnectedSitesModal)} />;
Nope :(

2023-08-22 13:15 UTC, GuillemGarciaDev commented on src/config/theme/theme.declarations.d.ts
> +        surf;
Outdated de l'altre PR 🙏🏻

2023-08-22 13:22 UTC, GuillemGarciaDev commented on src/module/common/component/navigation/BottomBar/MainBottomBarItem/MainBottomBarItem.styles.ts
> +        paddingHorizontal: 12,
<img width="89" alt="Screenshot 2023-08-22 at 15 22 01" src="https://github.com/Peersyst/near-mobile-wallet/assets/68080871/e65f8055-7110-40ef-932a-f585298ac2db">
Yep, sinó es veu bastant pocho

2023-08-22 13:40 UTC, GuillemGarciaDev commented on src/module/wallet/query/useGetAccountAccessKeys.ts
> +export default function useGetAccountAccessKeys(): UseQueryResult<ConnectedSite[], unknown> {
Afirmativo 🫡

2023-08-23 06:12 UTC, GuillemGarciaDev commented on src/module/wallet/hook/useParseConnectedSites.ts
> +            if (access_key.permission === "FullAccess") return translate("unknownAccount");
Perque en cas de que sigui tipus `FunctionCall` aleshores es passen 3 parametres: 

- allowance: quantitat de gas que permets utilitzar
- methodNames: metodes del smart contract que pot utilitzar 
- receiverId: address del smart contract que es vol utilitzar

2023-08-23 09:16 UTC, AgustinMJ requested changes

2023-08-23 09:16 UTC, AgustinMJ commented on src/module/wallet/query/useGetConnectedSites.ts
> +    }, [accessKeys, parseConnectedSites]);
Si el fiquem com a dependency d'aquest `useMemo`, el `useParseConnectedSites` hauria de retornar també un `useMemo`, en cas contrari a cada rerender canviarà la referència de `parseConnectedSites` i triggerejarà el càlcul

2023-08-23 09:42 UTC, AgustinMJ approved these changes

2023-08-23 10:01 UTC, merged