[TA-1169] DApp container
Peersyst/near-mobile-wallet pull request #334
Opened 2023-08-28 11:02 UTC by GuillemGarciaDev

# [TA-1169] DApp container

## Tasks

- [[TA-1169] DApp container](https://www.notion.so/DApp-container-bb910489357341a5bff248693569bfb7?pvs=4)

## Changes

- `DApp` component to display dapp information
- `AnimatedActionable` component to make DApp be swipable
- `DisconnectableDApp` container that uses `AnimatedActionable` to disconnect dApps
- locale + tests + mocks

2023-08-29 08:39 UTC, AgustinMJ requested changes

2023-08-29 08:39 UTC, AgustinMJ commented on src/module/common/component/feedback/AnimatedActionable/AnimatedActionable.tsx
> +    const swipeableProps = {
No acabo d'entendre això🤔 Per què no fem que es pugui fer swipe en les dos direccions? Si només passes una `swipeRightAction` que només faci swipe right, si passes també una `swipeLeftAction` que pugui fer swipe left també. També molaria poder renderitzar varies actions en un costat, però bueno per ara no fa falta així que no cal🙂

2023-08-29 08:39 UTC, AgustinMJ commented on src/module/dapp/screen/DappsScreen/DAppsScreen.tsx
> +                        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAn1BMVEX///8AUf4AT/4ATv4ASP4LVvcAQP4APv4AQ/8ATP4AO/wARP4ARv4AOv0ARfsASf7x9vy7y/nI1vnk7PqTq/mds/nU3/rO2vnp
https://www.youtube.com/watch?v=q9zKYh8sY_E
Està mocked, no?

2023-08-29 08:39 UTC, AgustinMJ commented on src/module/signer/components/display/DApp/DApp.tsx
> +const DApp = ({ dapp, connected = false }: DAppProps): JSX.Element => {
En un mobil petit es veu bé? Potser queda molt gran, no?

2023-08-29 08:39 UTC, AgustinMJ commented on src/module/signer/components/display/DApp/DApp.types.ts
> +export enum DAppTag {
`DAppTag` i `DApp` haurien d'estar a un lloc més accessible com `src/module/signer/types.ts`

2023-08-29 08:39 UTC, AgustinMJ commented on src/module/signer/components/feedback/DisconnectableDApp/hooks/useDisconnectableDAppStyles.ts
S'utilitza això? Igualment, no és millor fer styled components?

2023-08-29 10:02 UTC, GuillemGarciaDev commented on src/module/dapp/screen/DappsScreen/DAppsScreen.tsx
> +                        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAn1BMVEX///8AUf4AT/4ATv4ASP4LVvcAQP4APv4AQ/8ATP4AO/wARP4ARv4AOv0ARfsASf7x9vy7y/nI1vnk7PqTq/mds/nU3/rO2vnp
Si 😂 , a la següent PR ja estan totes a la config

2023-08-29 10:02 UTC, GuillemGarciaDev commented on src/module/signer/components/display/DApp/DApp.tsx
> +const DApp = ({ dapp, connected = false }: DAppProps): JSX.Element => {
Ho he provat tot amb el iphone SE i es veu bé

2023-08-29 11:46 UTC, GuillemGarciaDev commented on src/module/signer/components/feedback/DisconnectableDApp/hooks/useDisconnectableDAppStyles.ts
Refactored 🚜 

Crec que queda més clean així

2023-08-30 06:12 UTC, AgustinMJ approved these changes

2023-08-30 06:16 UTC, merged