[TA-1170] DApp list
Peersyst/near-mobile-wallet pull request #335
Opened 2023-08-28 13:39 UTC by GuillemGarciaDev

# [TA-1170] DApp list

## Tasks

- [[TA-1170] DApp list](https://www.notion.so/DApp-list-3b6cf1af50b1482291498d260310cfbf?pvs=4)

## Dependencies

#334 

## Changes

- new `DisconnectableDAppList` component
- `RecommendedDApps` container using `useRecommendedDApps` hook
- updated config with `recommendedDApps` field
- updated locale + testing

2023-08-29 08:44 UTC, AgustinMJ requested changes

2023-08-29 08:44 UTC, AgustinMJ commented on src/config/configs/config.dev.json
> +        "recommendedDApps": [
Les podem ficar a `config.base.json`, no?

2023-08-29 08:44 UTC, AgustinMJ commented on src/module/signer/hooks/useRecommendedDApps.ts
> +    const { recommendedDApps } = useConfig("signerFeature");
El `useConfig` està deprecated (a NEAR encara no perquè és del paleolitic, però algun dia ho estarà jajaja). Pots fer directament `<DisconnectableDAppList dapps={config.signerFeature.recomendedDaps} />`

2023-08-29 12:11 UTC, GuillemGarciaDev commented on src/config/configs/config.dev.json
> +        "recommendedDApps": [
La cosa es que encara que les fiquem, s'hauràn de mantindre a totes les configs perque tota la config de la `signerFeature` esta agrupada 🤔

2023-08-30 06:14 UTC, AgustinMJ commented on src/config/configs/config.dev.json
> +        "recommendedDApps": [
És veritat🤔 és lo dolent de fer configs agrupades. Hauriem de millorar les configs a algo com en el backend. De moment ho deixem així👍🏻

2023-08-30 06:14 UTC, AgustinMJ approved these changes

2023-08-30 06:16 UTC, merged