[TA-1171] DApp category select + search
Peersyst/near-mobile-wallet pull request #336
Opened 2023-08-29 09:53 UTC by GuillemGarciaDev

# [TA-1171] DApp category select + search

## Tasks

- [[TA-1171] DApp category select + search](https://www.notion.so/DApp-category-select-search-dae3767fe8384dc7aecfdaef01f7f3c8?pvs=4)

## Dependencies

#335 

## Changes

- `useRecommendedDApps` updated with dApp filtering
- `useRecommendedDAppsFilters` hook
- `SearchBar` component
- `DAppTagSelect` component
- testing updated + locale

2023-08-30 06:26 UTC, AgustinMJ requested changes

2023-08-30 06:26 UTC, AgustinMJ commented on src/module/signer/components/input/DAppTagSelect/DAppTagSelect.styles.ts
> +    minWidth: "33%",
Ara que penso el `minWidth` , `flex` i`maxWidth` s'hauria de donar amb un estil des de `RecommendedDApps`, ja que si vulguessim utilitzar aquest select a un altre lloc tindria una width implícita que probablement no voldriem

2023-08-30 06:26 UTC, AgustinMJ commented on src/module/signer/components/input/DAppTagSelect/DAppTagSelect.styles.ts
> +    minWidth: "33%",
Ara que penso el `minWidth` , `flex` i`maxWidth` s'hauria de donar amb un estil des de `RecommendedDApps`, ja que si vulguessim utilitzar aquest select a un altre lloc tindria una width implícita que probablement no voldriem

2023-08-30 06:26 UTC, AgustinMJ commented on src/module/signer/hooks/useRecommendedDApps.ts
> +    return recommendedDApps.filter(
Això potser s'hauria de ficar en un `useMemo` per si l'array es molt gran. Si sempre serà un array petit llavors no cal el `useMemo`.

En realitat ojo amb fer un `useQuery` pel caching. Podem fer una promise, algo així:
```ts
return useQuery([Queries.RECOMMENDED_DAPPS, query, tag], new Promise(resolve => {
  const filteredRecommendedDapps = config.signerFeature.recommendedDapps.filter(...);
  resolve(filteredRecommendedDapps);
}))
```

2023-08-31 08:49 UTC, GuillemGarciaDev commented on src/module/signer/hooks/useRecommendedDApps.ts
> +    return recommendedDApps.filter(
Em mola bastant, provo a veure que tal

2023-08-31 08:58 UTC, GuillemGarciaDev commented on src/module/signer/components/input/DAppTagSelect/DAppTagSelect.styles.ts
> +    minWidth: "33%",
True

2023-09-01 06:40 UTC, AgustinMJ approved these changes

2023-09-01 06:40 UTC, merged