[TA-1167] Re-style AddKey action modal
Peersyst/near-mobile-wallet pull request #338
Opened 2023-08-30 14:11 UTC by GuillemGarciaDev

# [TA-1167] Re-style AddKey action modal

## Tasks

- [[TA-1167] Re-style AddKey action modal](https://www.notion.so/Re-style-AddKey-action-modal-d3cdb7a73ad146538c4f6f7399e6a4c3?pvs=4)

## Dependencies

#335 

## Changes

- `signerFeature` config with new fields
- Updated `SignModalScaffold` with styled`SwipeButton`
- `AddKeyDetails` component update
- `PermissionField` component
- `FunctionCallDetails` component
- `SignerWalletSelector` container that uses new state `signRequestState`
- `ActionDetailField` component to list contractId and allowance fields of `AddKeyParams`
- recfactored `ActionDetailsScaffold` to handle new component `ActionPreview`
- locale + testing update

2023-08-30 15:51 UTC, AgustinMJ requested changes

2023-08-30 15:51 UTC, AgustinMJ commented on src/module/common/component/feedback/SwipeButton/SwipeButton.styles.ts
> +    height: 52,
El `SwipeButton` no té `size`?

2023-08-30 15:51 UTC, AgustinMJ commented on src/module/common/component/navigation/BottomBar/BottomBarQRScanner/BottomBarQRScanner.tsx
> +            {open && <QrScanner open={open} onClose={() => setOpen(false)} onScan={({ data }) => handleScan(data)} />}
Per què fa falta el `open &&`?

2023-08-30 15:51 UTC, AgustinMJ commented on src/module/signer/components/display/ActionDetailField/ActionDetailField.styles.ts
> +export const ActionDetailIcon = styledWithAs(Icon)(({ theme }) => ({
Millor un `ElementStyler` sense el `styledWithAs` que és super unstable

2023-08-30 15:51 UTC, AgustinMJ commented on src/module/signer/components/display/ActionPreview/ActionPreview.styles.ts
> +export const ActionPreviewIcon = styledWithAs(Icon)(({ theme }) => ({
El mateix del `styledWithAs` i `ElementStyler`

2023-08-30 15:51 UTC, AgustinMJ commented on src/module/signer/components/display/FunctionCallDetails/FunctionCallDetails.tsx
> +                    <ActionDetailField label={translate("contract")} content={receiverId} leftIcon={ClipboardListIcon} />
Aquí el més probable és que es vulgui que el contract sigui un link al explorer. Hauria de ser un `BlockchainLink` de type `contract` o una cosa així

2023-08-30 15:51 UTC, AgustinMJ commented on src/module/signer/components/display/PermissionField/PermissionField.types.tsx
> +export const PermissionIcons: Record<PermissionFieldType, ReactElement> = {
Això no hauria d'estar a types. Podem fer un `PermissionIcons.tsx` a la mateixa carpeta per exemple

2023-08-30 15:51 UTC, AgustinMJ commented on src/module/signer/components/layout/SignModalScaffold/SignModalScaffold.tsx
Ara que em fixo el nom d'aquest component potser hauria de ser `SignatureScaffold` o algo així perquè no té per què renderitzar-se a un `Modal`

2023-08-30 15:51 UTC, AgustinMJ commented on src/module/signer/state/SignRequestState.ts
> +const signRequestState = atom<SignRequestState>({
Per què ha de ser un `atom` això? No seria millor fer que la pantalla de la firma pasés el `signerWalletIndex` a la següent? D'aquesta manera ens estalviariem haver d'estar netejant el state i que aquest estigui disponible a qualsevol lloc de la app, que no hauria

2023-08-31 12:51 UTC, GuillemGarciaDev commented on src/module/signer/components/display/ActionDetailField/ActionDetailField.tsx
> +                <Typography variant="body3Regular" style={{ paddingLeft: 36 }} light>
Amb el SE es veu be pero al limit. No obstant, aquest padding 36 es degut al tamany del `LeftIcon` i el gap de la row

2023-08-31 13:01 UTC, GuillemGarciaDev commented on src/module/signer/state/SignRequestState.ts
> +const signRequestState = atom<SignRequestState>({
Aquest state no s'utilitza entre cap pantalla, sino unicament per a poder gestionar el index del wallet que es selecciona amb el `WalletSelector` per a que l'utilitzi el `serviceInstance` alhora de fer la signature.

Potser es millor utilitzar un `useContext`, perque si el fessim per prop drilling totes les screens de details haurien de tindre la prop de `signerWalletIndex`, que nomes es utilitzada per la `AddKeyDetails` (per fer signIn)

Que penses? 🤔

2023-08-31 13:06 UTC, GuillemGarciaDev commented on src/module/signer/components/display/FunctionCallDetails/FunctionCallDetails.tsx
> +                    <ActionDetailField label={translate("contract")} content={receiverId} leftIcon={ClipboardListIcon} />
Doncs potser cal fer un refactor al `BlockchainAddress`, perque amb l'explorer que tenim a la config no es poden visualizar les dades importants dels smart contracts, com els methods

https://explorer.testnet.near.org/accounts/guest-book.testnet

En canvi, aquest altre explorer proporciona mes info dels smart contracts

https://testnet.nearblocks.io/address/guest-book.testnet#contract

2023-08-31 14:53 UTC, AgustinMJ commented on src/module/signer/components/display/FunctionCallDetails/FunctionCallDetails.tsx
> +                    <ActionDetailField label={translate("contract")} content={receiverId} leftIcon={ClipboardListIcon} />
Fico una tasca

2023-08-31 14:57 UTC, AgustinMJ commented on src/module/signer/components/layout/SignModalScaffold/SignModalScaffold.tsx
Falta canviar el nom dels arxius a `SignatureScaffold`

2023-08-31 14:57 UTC, AgustinMJ commented on src/module/signer/state/SignRequestState.ts
> +const signRequestState = atom<SignRequestState>({
Les dos opcions em semblen bé, com tu vegis👍🏻

2023-09-01 06:45 UTC, AgustinMJ approved these changes

2023-09-01 07:21 UTC, merged