[TA-2149] Update dApps list
Peersyst/near-mobile-wallet pull request #401
Opened 2024-02-07 09:44 UTC by GuillemGarciaDev

# [TA-2149] Update dApps list

## Changes

- updated `recommendedDApps` on all configs

2024-02-07 13:58 UTC, AgustinMJ approved these changes

2024-02-07 13:59 UTC, JordiParraCrespo requested changes

2024-02-07 13:59 UTC, JordiParraCrespo commented on src/config/configs/config.staging.json
>          "backendUrl": "https://near-mobile-signer-backend.peersyst.tech",
Revisar el `backendUrl`

2024-02-07 13:59 UTC, JordiParraCrespo commented on src/config/configs/config.base.json
> +                "contractId": ""
:eye: Revisar això bé

2024-02-08 09:40 UTC, JordiParraCrespo approved these changes

2024-02-08 11:09 UTC, merged