[TA-2202] Upgrade near-api-js
Peersyst/near-mobile-wallet pull request #408
Opened 2024-02-09 12:28 UTC by silvap-javier

# [TA-2202] Upgrade near-api-js

## Issues

closes #

## Dependencies

#

## Changes

-

2024-02-09 16:39 UTC, GuillemGarciaDev requested changes

2024-02-09 16:39 UTC, GuillemGarciaDev commented on src/module/sdk/NearSdkService/NearSdkService.ts
> +        return KeyPair.fromString(secretKey) as KeyPairEd25519;
Creo que hay que crearla con la constructora de `KeyPairEd25519`:

`return new KeyPairEd25519(secretKey)`

2024-02-10 08:29 UTC, silvap-javier commented on src/module/sdk/NearSdkService/NearSdkService.ts
> +        return KeyPair.fromString(secretKey) as KeyPairEd25519;
Lo he probado, pero el cambio mas significativo es ese. 

https://near.github.io/near-api-js/classes/near_api_js.utils.KeyPairEd25519.html

Ahora mismo existen 3 properties : 

- extendedSecretKey
- publicKey
- secretKey

El contrstructor de KeyPairEd25519 espera una extendedSecretKey, y actualmente eso no se utiliza.

Por tal motivo leyendo y hablando con Jordi, vimo que dentro del refactor que hicieron se puede usar la libreria interna de KeyPair, que si utiliza la secretKey.

Luego de esto, estuve realizando varias pruebas y si que va todo correcto

2024-07-26 10:02 UTC, GuillemGarciaDev approved these changes

2024-07-26 10:02 UTC, merged