[TA-2253] Refactor Settings move SettingsStorage to frontend 2.0
Peersyst/near-mobile-wallet pull request #429
Opened 2024-02-18 17:29 UTC by silvap-javier

# [TA-2253] Refactor Settings move SettingsStorage to frontend 2.0

## Issues

closes #

## Dependencies

#

## Changes

-

2024-02-22 11:17 UTC, JordiParraCrespo requested changes
Buen trabajo pablete!!

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/module/common/query/useLoad.ts
> +            const allSettingsStored = await ControllerFactory.settingsController.getAllSettings();
Guay!! Dos cosas:
- Añadir los comments de refactor.
- *storageSettings better que `allSettingsStored`.

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/module/settings/components/core/BiometricsSwitch/BiometricsSwitch.tsx
> +        ControllerFactory.settingsController.set({ biometrics });
Comment

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/module/settings/components/core/DeleteData/DeleteData.tsx
> +        ControllerFactory.settingsController.clear();
Comment + missing `await`

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/module/settings/components/core/SelectFiat/SelectFiat.tsx
> +        ControllerFactory.settingsController.set({ fiat });
comment

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/module/settings/components/core/SelectLocale/SelectLocale.tsx
> +        ControllerFactory.settingsController.set({ locale: value });
comment

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/module/wallet/hook/useChangeNetwork.ts
> +        await Promise.all([ControllerFactory.settingsController.set({ network }), new Promise((resolve) => setTimeout(resolve, 2000))]);
comment

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/refactor/domain/settings/state/settingsState.ts
> +export type FiatCurrencyType = "cny" | "usd" | "eur" | "jpy" | "gbp" | "rub" | "uah" | "idr";
Los types deberían ir en algun sitio de `types` o `models`.

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/refactor/test/domain/settings/controller/SettingsController.spec.ts
> +            const settings = {
Molaria tener un mock

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/refactor/test/domain/settings/controller/SettingsController.spec.ts
> +            } as ISettingsState;
Xq necesita el `as` ?

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/refactor/test/mocks/settings/SettingsController.mock.ts
> +export const SettingsControllerMock = createMock<ISettingsController>({
=)

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/refactor/ui/locale/pluguins/LanguageDetectorPlugin/LanguageDetectorPlugin.ts
> +        const storedLocale = await ControllerFactory.settingsController?.getLocale();
:eye: Guay! Revisar que funcione bien el i18n que puede dar problemas!

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/refactor/domain/adapter/RepositoryFactory.ts
> +    settingsRepository: () => new SettingRepository(),
:smile:

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/refactor/test/domain/settings/controller/SettingsController.spec.ts
> +    const settingsRepositoryMock = new SettingsRepositoryMock();
:smile:

2024-02-22 11:17 UTC, JordiParraCrespo commented on src/refactor/domain/settings/state/settingsState.ts
> +export type FiatCurrencyType = "cny" | "usd" | "eur" | "jpy" | "gbp" | "rub" | "uah" | "idr";
@AgustinMJ

2024-02-22 11:21 UTC, AgustinMJ commented on src/refactor/domain/settings/state/settingsState.ts
> +export type FiatCurrencyType = "cny" | "usd" | "eur" | "jpy" | "gbp" | "rub" | "uah" | "idr";
Exacto, quizá podemos poner el `FiatCurrencyType` y `NetworkType` en `src/common/types`

2024-02-23 10:51 UTC, silvap-javier commented on src/module/common/query/useLoad.ts
> +            const allSettingsStored = await ControllerFactory.settingsController.getAllSettings();
Done

2024-02-23 10:51 UTC, silvap-javier commented on src/module/settings/components/core/BiometricsSwitch/BiometricsSwitch.tsx
> +        ControllerFactory.settingsController.set({ biometrics });
Done

2024-02-23 10:52 UTC, silvap-javier commented on src/module/settings/components/core/DeleteData/DeleteData.tsx
> +        ControllerFactory.settingsController.clear();
done

2024-02-23 10:52 UTC, silvap-javier commented on src/module/settings/components/core/SelectFiat/SelectFiat.tsx
> +        ControllerFactory.settingsController.set({ fiat });
done

2024-02-23 10:52 UTC, silvap-javier commented on src/module/settings/components/core/SelectLocale/SelectLocale.tsx
> +        ControllerFactory.settingsController.set({ locale: value });
done

2024-02-23 10:52 UTC, silvap-javier commented on src/module/wallet/hook/useChangeNetwork.ts
> +        await Promise.all([ControllerFactory.settingsController.set({ network }), new Promise((resolve) => setTimeout(resolve, 2000))]);
done

2024-02-23 11:00 UTC, silvap-javier commented on src/refactor/domain/settings/state/settingsState.ts
> +export type FiatCurrencyType = "cny" | "usd" | "eur" | "jpy" | "gbp" | "rub" | "uah" | "idr";
Done

2024-02-23 11:20 UTC, silvap-javier commented on src/refactor/test/domain/settings/controller/SettingsController.spec.ts
> +            const settings = {
Done

2024-02-23 11:21 UTC, silvap-javier commented on src/refactor/ui/locale/pluguins/LanguageDetectorPlugin/LanguageDetectorPlugin.ts
> +        const storedLocale = await ControllerFactory.settingsController?.getLocale();
Sep, lo he revisado :)

2024-02-23 11:43 UTC, JordiParraCrespo commented on src/module/common/types.ts
> +import { Chains } from "near-peersyst-sdk";
Aquí copiar el enum mejor que el plan es borrar este sdk

2024-02-23 11:52 UTC, silvap-javier commented on src/module/common/types.ts
> +import { Chains } from "near-peersyst-sdk";
Done

2024-10-14 09:49 UTC, closed without merging