[TA-2258] Remove `system` transactions
Peersyst/near-mobile-wallet pull request #430
Opened 2024-02-19 13:25 UTC by obnol

# [TA-2258] Remove `system` transactions

## Changes

- Add an `if` statement to check the `predecessor_account_id` of a transaction in `NearBlocksService` to exclude `system` transactions

2024-02-19 14:05 UTC, AgustinMJ approved these changes

2024-02-20 08:33 UTC, JordiParraCrespo requested changes

2024-02-20 08:33 UTC, JordiParraCrespo commented on src/module/sdk/NearApiService/NearBlocksService.ts
> -            const baseTransaction: TransactionWithoutActions = {
Ja es pot treure el comment de //es-lint....

Tmb cal revisar si surten prous txs a la llista, igual cal augmentar el `page_size`? Si ho veus bé borrant el comment hi ha prou

2024-02-20 08:51 UTC, JordiParraCrespo approved these changes

2024-02-20 08:52 UTC, merged