refactor(app): add fallback api calls with kitwallet magic
Peersyst/near-mobile-wallet pull request #437
Opened 2024-02-23 11:35 UTC by JordiParraCrespo

2024-02-27 08:09 UTC, AgustinMJ requested changes

2024-02-27 08:09 UTC, AgustinMJ commented on src/module/sdk/NearApiService/ApiService.ts
> +            oldAccounts = await timeoutPromise(oldAccountsPromise, 3000);
Ficaria el `3000` a la config rollo `kitwalletRequestTimeout`

2024-02-27 08:09 UTC, AgustinMJ commented on src/module/sdk/NearApiService/ApiService.ts
> +                contractIds = (
Aquí també hem de ficar `timeoutPromise`, no?

2024-02-27 08:09 UTC, AgustinMJ commented on src/module/sdk/NearApiService/ApiService.ts
> +                contractIds = (
I aquí

2024-02-27 08:09 UTC, AgustinMJ commented on src/module/sdk/NearApiService/ApiService.ts
> +                const txs = await this.handleFetch<ActionApiDto[]>(`${this.baseUrl}/account/${address}/activity`);
I aquí :P. Es fa una mica raro que no tinguem un `KitwalletService` que ja inclogui el `timeoutPromise` per defecte a totes les requests en plan en el seu `handleFetch`

2024-02-28 08:31 UTC, JordiParraCrespo commented on src/module/sdk/NearApiService/ApiService.ts
> +            oldAccounts = await timeoutPromise(oldAccountsPromise, 3000);
done

2024-02-28 08:31 UTC, JordiParraCrespo commented on src/module/sdk/NearApiService/ApiService.ts
> +                contractIds = (
done

2024-02-28 08:32 UTC, JordiParraCrespo commented on src/module/sdk/NearApiService/ApiService.ts
> +                contractIds = (
done

2024-02-28 08:32 UTC, JordiParraCrespo commented on src/module/sdk/NearApiService/ApiService.ts
> +                const txs = await this.handleFetch<ActionApiDto[]>(`${this.baseUrl}/account/${address}/activity`);
Molt ben vist!! Refactorizat!

2024-02-28 09:03 UTC, AgustinMJ approved these changes

2024-02-28 09:04 UTC, merged