[TA-2362] [TA-2382] feat : add swap button in account card
Peersyst/near-mobile-wallet pull request #450
Opened 2024-03-13 13:15 UTC by silvap-javier

# [TA-2362] [TA-2382] feat : add swap button in account card

## Issues

closes #

## Dependencies

#410 

## Changes

- add swap button
- add in all locale word : "swap"

2024-03-18 14:55 UTC, AgustinMJ approved these changes

2024-03-18 17:10 UTC, silvap-javier commented
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/e9d2b38f-9fd6-414d-a241-11678955435a)

2024-03-19 08:12 UTC, JordiParraCrespo requested changes
Ha quedado muy chulo congrats!! 🇦🇷 
Te dejo algunos detalles del componente base del icono con el texto que creo q se pueden mejorar 😄

2024-03-19 08:12 UTC, JordiParraCrespo commented on src/module/common/component/input/WalletButtonIcon/WalletButtonIcon.tsx
> +const WalletButtonIcon = ({ label, Icon, onPress, ...rest }: WalletButtonIconProps): JSX.Element => {
Aquí cambiaría el naming a `LabeledIconButton`.

2024-03-19 08:12 UTC, JordiParraCrespo commented on src/module/common/component/input/WalletButtonIcon/WalletButtonIcon.tsx
> +export interface WalletButtonIconProps extends ButtonProps {
Bien el extends de las `ButtonProps`. Nse si aquí extendería las `IconButtonProps` 🤔

2024-03-19 08:12 UTC, JordiParraCrespo commented on src/module/common/component/input/WalletButtonIcon/WalletButtonIcon.tsx
> +        <Col gap={6} alignItems="center">
Quizá debería ser clickeable toda la `Col`, ya que ahora si clicas al texto no se ejecturá la acción.

2024-03-19 08:12 UTC, JordiParraCrespo commented on src/module/common/component/input/WalletButtonIcon/WalletButtonIcon.tsx
> +            <Placeholder variant="body3Strong">{label}</Placeholder>
Esto debería ser una `Typography`.

2024-03-19 08:14 UTC, JordiParraCrespo commented
Cuando hagas los cambios lo reviso en algún phone más, ya que en los diseños apararecen los botones con un pelin más de gap y nse si le añadimos más en los dispositivos peqes se verá mal...

2024-03-20 08:21 UTC, JordiParraCrespo commented on src/module/common/component/input/LabeledIconButton/LabeledIconButton.tsx
> +                <LabeledIconButtonButton variant={variant}>
Faltaria hacer el componente de `IconButton` con las variants no?

2024-03-20 08:23 UTC, silvap-javier commented on src/module/common/component/input/LabeledIconButton/LabeledIconButton.tsx
> +                <LabeledIconButtonButton variant={variant}>
Ayer hablamos con @AgustinMJ y pensamos que es mejor asi, que el IconButton no tiene que tener styles

2024-03-20 13:34 UTC, silvap-javier commented
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/8fdc964c-1d03-4e79-9ed4-d85add38ebcf)

Lo he ajustado un pelin mas, pero mas que eso ya se ve mal

2024-03-21 07:44 UTC, JordiParraCrespo approved these changes

2024-03-21 07:45 UTC, merged