[TA-2364] : Feat/change network in header
Peersyst/near-mobile-wallet pull request #452
Opened 2024-03-14 10:07 UTC by silvap-javier

# [TA-2364] : Feat/change network in header

## Issues

closes #

## Dependencies

#410 

## Changes

- add onPress in chip and refactor SelectNetwork to call from external component

2024-03-14 11:11 UTC, silvap-javier commented on src/module/common/component/navigation/Header/Header.tsx
> +                        onPress={() => setOpenSelect(true)}
Agus, me ha comentado, que no pongamos el Icon :)

2024-03-18 13:37 UTC, silvap-javier commented on src/module/common/component/navigation/Header/Header.tsx
> +                    <SelectNetwork style={{ display: "none" }} isOpenExternal={openSelect} setOpenExternal={setOpenSelect} />
Cree un nuevo component el ChipNetworkSelector, pero igual hay que ponerle el display none. Creo que es la mejor solucion, en cuanto a pasarle el render value en vacio no funciona.

2024-03-18 13:39 UTC, silvap-javier commented on src/module/settings/components/core/SelectNetwork/SelectNetwork.tsx
> +export interface SelectNetworkI {
Perfect, solo deje la llamada del setOpenExternal que es necesario, si use useControlled luego no funciona en el settings

2024-03-18 13:39 UTC, silvap-javier commented on src/module/settings/components/core/SelectNetwork/SelectNetwork.tsx
>      const [openSelect, setOpenSelect] = useState(false);
Ahi en el comment de arriba deje cositas

2024-03-19 08:26 UTC, JordiParraCrespo requested changes
Buen trabajo! Revisa lo del `useControlled` y un poco el naming. Tmb veo más limpio intentar pasarle alguna prop al `Select` que ponerlo en display:none, si no te acaba de salir lo del `renderValue` llámame y lo miramos 😄

2024-03-19 08:26 UTC, JordiParraCrespo commented on src/module/settings/components/core/ChipSelectNetwork/ChipSelectNetwork.styles.ts
> +export const ChipNetwork = styled(Chip)<{ type: NetworkType }>(({ theme, type }) => ({
Le diría `NetworkChip`.

2024-03-19 08:26 UTC, JordiParraCrespo commented on src/module/settings/components/core/SelectNetwork/SelectNetwork.tsx
> +    setOpenExternal?: (open: boolean) => void;
- Esto se tendría que controlar con un `useControlled`. Con las props que ya vienen del `Select`. 
- El style no ha de ser any. Siempre `any`=⚠️ . El `Select` debería traer ya una prop de `style` no?

2024-03-19 08:26 UTC, JordiParraCrespo commented on src/module/settings/components/core/SelectNetwork/SelectNetwork.tsx
> +export interface SelectNetworkI extends SelectProps<NetworkType> {
`SelectNetworkProps` los parámetros de un componente siempre se les llama `Props`.

2024-03-19 08:26 UTC, JordiParraCrespo commented on src/module/settings/components/core/SelectNetwork/SelectNetwork.tsx
> +const SelectNetwork = ({ style, setOpenExternal, ...rest }: SelectNetworkI): JSX.Element => {
El `style` ya viene con el `...rest` no hace falta hacer deconstructing y sacarlo para luego pasarlo otra vez.

2024-03-19 08:26 UTC, JordiParraCrespo commented on src/module/settings/components/core/SelectNetwork/SelectNetwork.tsx
> +        setOpenExternal && setOpenExternal(false);
Esto no hace falta con el `useControlled`.

2024-03-19 08:26 UTC, JordiParraCrespo commented on src/module/settings/components/core/ChipSelectNetwork/ChipSelectNetwork.tsx
> +        <Row style={{ position: "absolute", left: 8 }}>
Estos estilos se deberían pasar desde fuera ya que si quieres reusar el componente siempre se pondrá con `position: absolute`.

2024-03-19 08:26 UTC, JordiParraCrespo commented on src/module/settings/components/core/ChipSelectNetwork/ChipSelectNetwork.tsx
> +            <SelectNetwork style={{ display: "none" }} setOpenExternal={setOpenSelect} open={openSelect} />
En vez del `style={{ display: "none" }}` has probado de pasarle el `NetworkChip` con la prop de `renderValue`?

2024-03-19 08:26 UTC, JordiParraCrespo commented on src/module/common/component/navigation/Header/Header.tsx
> +                <ChipSelectNetwork />
Muy bien el componente 🔝

2024-03-19 08:27 UTC, silvap-javier commented on src/module/common/component/navigation/Header/Header.tsx
> +                        onPress={() => setOpenSelect(true)}
Sep, Asi es Agus :)

2024-03-19 10:06 UTC, silvap-javier commented on src/module/settings/components/core/ChipSelectNetwork/ChipSelectNetwork.styles.ts
> +export const ChipNetwork = styled(Chip)<{ type: NetworkType }>(({ theme, type }) => ({
Done

2024-03-19 10:06 UTC, silvap-javier commented on src/module/settings/components/core/ChipSelectNetwork/ChipSelectNetwork.tsx
> +        <Row style={{ position: "absolute", left: 8 }}>
Done

2024-03-19 10:06 UTC, silvap-javier commented on src/module/settings/components/core/ChipSelectNetwork/ChipSelectNetwork.tsx
> +            <SelectNetwork style={{ display: "none" }} setOpenExternal={setOpenSelect} open={openSelect} />
Sep, ya lo vimos, tenemos quie mandarselo asi por que sino se renderiza

2024-03-19 10:06 UTC, silvap-javier commented on src/module/settings/components/core/SelectNetwork/SelectNetwork.tsx
> +export interface SelectNetworkI extends SelectProps<NetworkType> {
Done

2024-03-19 10:06 UTC, silvap-javier commented on src/module/settings/components/core/SelectNetwork/SelectNetwork.tsx
> +    setOpenExternal?: (open: boolean) => void;
Done

2024-03-19 10:06 UTC, silvap-javier commented on src/module/settings/components/core/SelectNetwork/SelectNetwork.tsx
> +const SelectNetwork = ({ style, setOpenExternal, ...rest }: SelectNetworkI): JSX.Element => {
Done

2024-03-19 10:06 UTC, silvap-javier commented on src/module/settings/components/core/SelectNetwork/SelectNetwork.tsx
> +        setOpenExternal && setOpenExternal(false);
Done

2024-03-19 10:10 UTC, silvap-javier commented on src/module/common/component/navigation/Header/Header.tsx
> +                        onPress={() => setOpenSelect(true)}
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/b4357666-7ddc-4b9c-a37b-a8e249e91fe1)

2024-03-19 10:10 UTC, silvap-javier commented
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/13bed91a-5fd4-4261-a58a-2e0822408028)

2024-03-20 09:00 UTC, JordiParraCrespo approved these changes

2024-03-20 09:08 UTC, merged