[TA-2365] : App(fix) move imported badge in BaseWalletCard
Peersyst/near-mobile-wallet pull request #453
Opened 2024-03-14 11:08 UTC by silvap-javier

# [TA-2365] : App(fix) move imported badge in BaseWalletCard

## Issues

closes #

## Dependencies

#410 

## Changes

- Move imported badge in BaseWalletCard and remove in Account

2024-03-18 15:39 UTC, AgustinMJ requested changes

2024-03-18 15:39 UTC, AgustinMJ commented on src/module/wallet/component/display/Account/Account.tsx
> -export interface AccountProps extends Omit<BlockchainAddressProps, "type" | "copy"> {
Estas props habría que dejarlas, ya que el `type` que queremos que haga omit, el `copy` se puede quitar i el `{ imported?: boolean }` también

2024-03-18 15:39 UTC, AgustinMJ commented on src/module/wallet/component/display/Account/Account.tsx
>          <Row style={{ maxWidth: "100%", ...style }} gap={"2%"}>
Quizás no hace falta ya esta `Row`, el `gap` seguro que no

2024-03-18 15:39 UTC, AgustinMJ commented on src/module/common/component/surface/BaseWalletCard/BaseWalletCard.tsx
> +            {imported && <Chip label={translate("imported").toUpperCase()} variant="glass" size="sm" style={{ alignSelf: "flex-end" }} />}
Fíjate que el `Chip` así hace que se desplace todo hacia abajo y quede mal. Hay que hacer dos cosas para que quede bien:

1. Poner el `Chip` con `position: absolute; top: 0; right: 0;` (lo mejor es hacer un styled component)
2. Hay quitar el `gap` de `BaseWalletCardRoot` i usar otra `Col` para la `Account` i `footer`. Esto es necesario porque tenemos una implementación previa del `gap` antes de que `react-native` sacara la suya oficial. Esto hace que el `gap` tenga en cuenta los elementos con `position: absolute`. Por lo tanto, si no hacemos nada, la `BaseWalletCardRoot` pondrá un `gap` en el `Chip` aunque este tenga `position: absolute`. Hay que hacer algo como esto:

```jsx
<BaseWalletCardRoot>
        {!imported && (
            // El styled del Chip
            <ImportedWalletChip
                label={translate("imported").toUpperCase()}
                 ariant="glass"
                size="sm"
            />
        )}
        <Col gap={gap} style={{ width: "100%" }}>
            <Col style={{ width: "100%" }} alignItems="center" gap={10} justifyContent="center">
                <Account action="copy" address={account} variant="body2Strong" />
                {content}
            </Col>
            <Row justifyContent="center">{footer}</Row>
         </Col>
</BaseWalletCardRoot>
```

2024-03-18 17:25 UTC, silvap-javier commented on src/module/common/component/surface/BaseWalletCard/BaseWalletCard.tsx
> +            {imported && <Chip label={translate("imported").toUpperCase()} variant="glass" size="sm" style={{ alignSelf: "flex-end" }} />}
Perfect, no sabia lo del Gap, ya quedo implementado con un style component

2024-03-18 17:25 UTC, silvap-javier commented on src/module/wallet/component/display/Account/Account.tsx
> -export interface AccountProps extends Omit<BlockchainAddressProps, "type" | "copy"> {
Done

2024-03-18 17:25 UTC, silvap-javier commented on src/module/wallet/component/display/Account/Account.tsx
>          <Row style={{ maxWidth: "100%", ...style }} gap={"2%"}>
mmm es verdad, removi los dos

2024-03-19 08:15 UTC, AgustinMJ approved these changes

2024-03-19 08:16 UTC, merged