[TA-2363] [APP] feat : token details modal
Peersyst/near-mobile-wallet pull request #455
Opened 2024-03-19 10:22 UTC by silvap-javier

# [TA-2363] [APP] feat : token details modal

## Issues

closes #

## Dependencies

#450 

## Changes

- Add new component DetailsTokenModal
- Add onPress in TokenCard

2024-03-19 10:25 UTC, silvap-javier commented
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/09a03e8c-f81a-43d9-8ce4-f1a9eed93512)

2024-03-20 09:55 UTC, JordiParraCrespo requested changes
Buen trabajo!! Te dejo algunos comments 👍

2024-03-20 09:55 UTC, JordiParraCrespo commented on src/module/token/component/display/TokenBalance/TokenBalance.tsx
> +        <Col alignItems={alignItems} justifyContent="center" gap={2} flex={1}>
El estilo de `flex:1` se le debería de pasar desde fuera. 
X defecto los componentes deben de ser lo más versátiles posibles y si le metemos `flex:1` habrá situaciones done no queramos que ocupe todo el espacio posible. Es un caso similar de la anterior pr con el `position:absolute`.

2024-03-20 09:55 UTC, JordiParraCrespo commented on src/module/token/component/core/DetailsTokenModal/DetailsTokenModal.tsx
> +    const uriSwap = useGetSwapLink();
Esto debería ser un link espefício para el token en cuestión que creo que reffinance lo crea a partir del contract.
Por ejemplo este sería un link de ejemplo:
```
https://app.ref.finance/#blackdragon.tkn.near|near
```
Si te fijas seria así creo:
```
`https://app.ref.finance/#${contractId}|near`
```

2024-03-20 09:55 UTC, JordiParraCrespo commented on src/module/token/component/display/TokenBalance/TokenBalance.tsx
> +const TokenBalance = ({ token, alignItems = "flex-end" }: TokenBalanceProps): JSX.Element => {
Me gusta la idea de hacer un componente para el tokenBalance 🔝 
Igual añadiría la posibilidad de mostrar o no el icono sea opcional. Tmb deberías poder sobrescribir las props de la tipografia, como la variant, el `numberOfLines`...

2024-03-20 09:55 UTC, JordiParraCrespo commented on src/module/token/component/display/TokenHeader/TokenHeader.tsx
> +const TokenHeader = ({ token }: TokenHeaderProps): JSX.Element => {
Again bien la idea del componente 🔝 
1. Aquí le cambiaría el nombre del componente. Queda raro que sea: 
- TokenIcon + TokenName -> TokenHeader

Pregúntale al chat a ver si tiene alguna idea mejor 🤔 Tmb deberías añadir props de configuración como te he comentado antes, no?

2. Por otro lado, en el caso de que te estuvieras refiriendo al header del componente de `TokenCard`. Debería ser un componente dentro de la carpeta `TokenCard` y que se llamara `TokenCardHeader` que entonces si que solo aceptaría la prop del `token`.

Entiendo que la idea era la segunda opción.

2024-03-20 09:55 UTC, JordiParraCrespo commented on src/module/token/component/core/DetailsTokenModal/DetailsTokenModal.tsx
> +            navbar={{ back: true, title: <TokenHeader token={token} />, style: { justifyContent: "flex-start", paddingLeft: 30 } }}
Molaría que pudieras situar el `title` en el centro o en la izquierda desde dentro xq puede ser que se necesite en algún otro lugar que el `title` quede alineado a la izquierda.

2024-03-20 19:45 UTC, silvap-javier commented on src/module/token/component/core/DetailsTokenModal/DetailsTokenModal.tsx
> +    const uriSwap = useGetSwapLink();
Done

2024-03-22 13:41 UTC, JordiParraCrespo approved these changes

2024-03-22 13:49 UTC, merged