[TA-2401] [APP] feat : change send order
Peersyst/near-mobile-wallet pull request #456
Opened 2024-03-19 18:02 UTC by silvap-javier

# [TA-2401] [APP] feat : change send order

## Issues

closes #

## Dependencies

#455 

## Changes

- Change send order in sendModal

2024-03-20 10:29 UTC, JordiParraCrespo requested changes
Guay! Cambiaría solo de naming `currentaAsset` por `defaultAsset` El resto guay! 😄

2024-03-25 08:11 UTC, JordiParraCrespo requested changes

2024-03-25 08:11 UTC, JordiParraCrespo commented on src/module/transaction/screen/SendToAddressScreen/SendToAddressScreen.tsx
> +    const [currentSenderWalletIndex] = useState(defaultSenderWalletIndex);
No necesitas el estado aqui

2024-03-25 08:11 UTC, JordiParraCrespo commented on src/module/transaction/screen/SendToAddressScreen/SendToAddressScreen.tsx
> +    const [currentSenderWalletIndex] = useState(defaultSenderWalletIndex);
Puedes dejarlo como:
```
  const senderWalletIndex = sendState.senderWalletIndex ?? selectedWallet;
```

2024-03-25 09:13 UTC, silvap-javier commented on src/module/transaction/screen/SendToAddressScreen/SendToAddressScreen.tsx
> +    const [currentSenderWalletIndex] = useState(defaultSenderWalletIndex);
Done

2024-03-25 10:19 UTC, JordiParraCrespo approved these changes

2024-03-25 10:20 UTC, merged