[TA-2383] [TA-2384] [APP] : feat Restyle backup wallets page and refactor Alert
Peersyst/near-mobile-wallet pull request #457
Opened 2024-03-19 20:24 UTC by silvap-javier

# [TA-2383] [TA-2384] [APP] : feat Restyle backup wallets page and refactor Alert

## Issues

closes #

## Dependencies

#

## Changes

- Refactor Alert component
- Restyle backup wallets page

2024-03-19 20:25 UTC, silvap-javier commented
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/5c7df214-bed0-4059-bb3e-9f579f782481)

2024-03-19 20:25 UTC, silvap-javier commented
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/2470577d-4ff6-47fd-87dd-d22e4340315d)

2024-03-20 13:17 UTC, silvap-javier commented
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/018b3604-24a0-477e-876f-37c5c287665e)

2024-03-22 13:44 UTC, JordiParraCrespo requested changes
Revisar lo del `status`

2024-03-22 13:44 UTC, JordiParraCrespo commented on src/module/common/component/feedback/Alert/Alert.styles.ts
> +export const AlertRoot = styled(Alert)<AlertProps>(({ theme: { palette }, type, color }) => {
Aquí no se debería pasar el color no?

2024-03-22 13:44 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletsBackupAdvise/WalletsBackupAdvise.styles.ts
> +    color: theme.palette.primary,
Bien el primary! =)

2024-03-22 13:44 UTC, JordiParraCrespo commented on src/module/settings/components/core/ManualAccountImport/ManualAccountImport.tsx
> +import useTranslate from "module/common/hook/useTranslate";
Bien!=)

2024-03-22 13:44 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletsBackupAdvise/WalletsBackupAdvise.tsx
> +                            <Alert color="orange" type="success" content={<WalletsBackupAdviseAlertContent />}></Alert>
No debería ser `warning` o así?

2024-03-22 13:44 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletsBackupAdviseAlertContent/WalletsBackupAdviseAlertContent.tsx
> +            <Typography color="orange" variant="body3Strong">
Aquí igual mejor `status.warning`

2024-03-25 10:28 UTC, silvap-javier commented on src/module/wallet/component/core/WalletsBackupModal/WalletsBackupAdvise/WalletsBackupAdvise.tsx
> +                            <Alert color="orange" type="success" content={<WalletsBackupAdviseAlertContent />}></Alert>
Claro, es que por eso le he puesto el color, por que no hay una coincidencia con el type, entre el icon y el color, por ejemplo este, tiene un icono de success pero el color es el naranja.

2024-03-25 10:28 UTC, silvap-javier commented on src/module/wallet/component/core/WalletsBackupModal/WalletsBackupAdviseAlertContent/WalletsBackupAdviseAlertContent.tsx
> +            <Typography color="orange" variant="body3Strong">
Done, pero he cambiado el theme para que el warning ahora sea el orange

2024-03-25 10:28 UTC, silvap-javier commented on src/module/common/component/feedback/Alert/Alert.styles.ts
> +export const AlertRoot = styled(Alert)<AlertProps>(({ theme: { palette }, type, color }) => {
Te deje un comentario mas abajo sobre esto

2024-03-25 12:29 UTC, JordiParraCrespo requested changes
Ei Pablo he visto que hay dos veces donde se importa: 
```
import { useTranslate } from "module/common/hook/useTranslate";
```
No había quedado fixeado ya?

2024-03-25 12:29 UTC, JordiParraCrespo commented on src/config/theme/baseTheme.ts
> -        warning: "#FFC860",
En los otros lugares que estaba puesto el color anterior han cambiado a este? Xq es diferente?

2024-03-25 12:29 UTC, JordiParraCrespo commented on src/locale/locales/sw/common.json
> +    "backup_wallet_advise_text_2_text_2": "Ikiwa mtu amekuuliza nembo yako au ufunguo wako wa faragha, huenda wanataka tu kuiba akaunti yako.",
No me había fijado, igual puedes encontrar un mejor nombre para:
```
backup_wallet_advise_text_2_text_2
```

2024-03-25 12:29 UTC, JordiParraCrespo commented on src/locale/locales/es/common.json
> +    "backup_wallet_advise_text_2_text": "Recuerde que ni nosotros ni NEAR nunca le pediremos su mnemónico o clave privada. Solo usted debe conocerlos y nunca compartirlos con nadie.",
Nse si te lo había comentado ya xo igual se me borró pondría `mnemonic` no?

2024-03-25 12:29 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletsBackupAdvise/WalletsBackupAdvise.tsx
> +                            <Alert color="orange" type="success" content={<WalletsBackupAdviseAlertContent />}></Alert>
En ese caso deberías customizar el icono no el color ya que aquí se trata de `status:warning` ya que estás advertiendo al usuario no?

2024-03-25 19:29 UTC, silvap-javier commented
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/5854e531-ed6b-46b4-b02a-256a871c53e3)

2024-03-26 08:00 UTC, JordiParraCrespo requested changes

2024-03-26 08:00 UTC, JordiParraCrespo commented on src/module/common/hook/useDeviceSize.ts
> +        Dimensions.addEventListener("change", handleDimensionsChange);
Siempre que añades un `Listener` hay que dejar de suscribirse. En el caso del useEffect ha de hacerse en el return de lafunción.

2024-03-26 08:00 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletsBackupAdvise/WalletsBackupAdvise.styles.ts
> +    fontSize: size === DeviceSize.SMALL ? 30 : 50,
Esto mejor con las dimensions.

2024-03-26 08:00 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletsBackupAdvise/WalletsBackupAdvise.tsx
> +                <Col gap="3%" flex={1} style={{ paddingTop: deviceSize === DeviceSize.SMALL ? 0 : 25 }}>
Esto debería ser un styled component.

2024-03-26 08:00 UTC, JordiParraCrespo commented on src/module/common/hook/useDeviceSize.ts
> +        Dimensions.addEventListener("change", handleDimensionsChange);
Por otro lado tampoco hace falta que escuchemos los cambios del tamaño de pantalla

2024-03-26 08:00 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletsBackupAdvise/WalletsBackupAdvise.tsx
> +                                lineHeight: deviceSize === DeviceSize.SMALL ? 17 : 28,
Siempre dejamos la variant para el tamaño de la letra. 
En el caso de que se qisiera hacer adaptativo se debería de hacer en toda la app no screen por screen.
Si no cabe en tamaño pequeño anádele una `ScrollView`.

2024-03-26 08:00 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletsBackupAdviseAlertContent/WalletsBackupAdviseAlertContent.styles.ts
> +export const TypographyAdvise = styled(Typography)<{ size: DeviceSize }>(({ size }) => ({
Idem aquí

2024-03-26 08:00 UTC, JordiParraCrespo commented on src/locale/locales/es/common.json
> +    "backup_wallet_advise_description_2": "Si alguien le ha pedido su mnemonic o clave privada, probablemente solo quieran robar su cuenta.",
Bien el cambio de texto! =)

2024-03-26 10:29 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletsBackupAdviseAlertContent/WalletsBackupAdviseAlertContent.styles.ts
> +export const TypographyAdvise = styled(Typography)<{ size: DeviceSize }>(({ size }) => ({
Falta borrar esto

2024-03-26 11:42 UTC, JordiParraCrespo approved these changes

2024-03-26 11:42 UTC, merged