[TA-2387][APP] feat: add NotificationIcon
Peersyst/near-mobile-wallet pull request #458
Opened 2024-03-20 09:28 UTC by silvap-javier

# [TA-2387][APP] feat: add NotificationIcon

## Issues

closes #

## Dependencies

#

## Changes

- Add NotificacionIcon and remove Notificacion component

2024-03-20 09:36 UTC, silvap-javier commented
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/99796545-ae84-437a-b39f-e355678db68c)

2024-03-20 09:39 UTC, silvap-javier commented
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/fb5672e0-e91c-4537-b624-684adb35d037)

2024-03-22 13:48 UTC, JordiParraCrespo requested changes

2024-03-22 13:48 UTC, JordiParraCrespo commented on src/module/common/component/display/NotificationIcon/NotificationIcon.styles.ts
> +        borderColor: hasNotifications ? theme.palette.status.error : theme.palette.text,
Siempre que se renderiza esta con el `hasNotifications` a true no?

2024-03-22 13:48 UTC, JordiParraCrespo commented on src/module/common/component/display/NotificationIcon/NotificationIcon.styles.ts
> +    position: "relative",
Creo que en `ReactNative` ya te pone el `relative` x defecto, puedes revisarlo?

2024-03-22 13:48 UTC, JordiParraCrespo commented on src/module/common/component/display/NotificationIcon/NotificationIcon.tsx
> +            {hasNotifications && <AlertCircle testID={"activeCircle"} hasNotifications={hasNotifications} />}
el `testID` le pondría el mismo nombre que al componente

2024-03-22 13:49 UTC, JordiParraCrespo requested changes
Unos mini changes, pregunta: ¿¿Cuando tendrá las notis activas??

2024-03-25 10:18 UTC, silvap-javier commented on src/module/common/component/display/NotificationIcon/NotificationIcon.styles.ts
> +    position: "relative",
True

2024-03-25 10:18 UTC, silvap-javier commented on src/module/common/component/display/NotificationIcon/NotificationIcon.styles.ts
> +        borderColor: hasNotifications ? theme.palette.status.error : theme.palette.text,
True

2024-03-25 10:18 UTC, silvap-javier commented on src/module/common/component/display/NotificationIcon/NotificationIcon.tsx
> +            {hasNotifications && <AlertCircle testID={"activeCircle"} hasNotifications={hasNotifications} />}
o no tenerlo jaja, lo he sacado que no es necesario

2024-03-25 10:42 UTC, silvap-javier commented
> Unos mini changes, pregunta: ¿¿Cuando tendrá las notis activas??

Solamente cuando isBackupDone is true, ahora, pero me imagino que se puede usar mas adelante para otras opciones

2024-03-26 08:14 UTC, JordiParraCrespo commented on src/module/common/component/display/NotificationIcon/NotificationIcon.tsx
> +    style?: TextStyle;
Tmb esto sería `ViewStyle`

2024-03-26 09:39 UTC, JordiParraCrespo approved these changes

2024-03-26 09:46 UTC, merged