[TA-2386] [TA-2385] [App] feat : Skip backup option in verify mnemonic page and add isBackupDone in state and storage
Peersyst/near-mobile-wallet pull request #460
Opened 2024-03-21 14:33 UTC by silvap-javier

[TA-2386] [TA-2385] [App] feat : Skip backup option in verify mnemonic page and add isBackupDone in state and storage

## Issues

closes #

## Dependencies

#

## Changes

- Skip backup option in verify mnemonic page
- Skip backup domain & data-access
- Add setIsBackupDone when export mnemonic

2024-03-25 08:23 UTC, JordiParraCrespo requested changes

2024-03-25 08:23 UTC, JordiParraCrespo commented on src/locale/locales/en/common.json
> +    "IWillDoItLater": "I’ll do it later"
con `camelCase` siempre empieza en minuscula.

2024-03-25 08:23 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletPrivateKeyBackup/WalletPrivateKeyBackup.tsx
> +                WalletStorage.setIsBackupDone(true);
Aqui podria ser q se haga backup de una private key importada y que no se haga backup del mnemonic. Solo lo pondria para el caso del mnemonic.

2024-03-25 08:23 UTC, JordiParraCrespo commented on src/module/wallet/navigator/CreateWalletNavigatorGroup.tsx
> +                            onNextScreen={() => handleTabChange(CreateWalletScreens.SET_WALLET_PIN)}
No hace falta anyadir otro callBack que hace lo mismo no?

2024-03-25 08:23 UTC, JordiParraCrespo commented on src/module/wallet/screen/PickWalletMnemonicScreen/PickWalletMnemonicScreen.tsx
> +    onNextScreen: () => void;
Aqui con uno de los dos callbacks hay suficiente.

2024-03-25 08:23 UTC, JordiParraCrespo commented on src/module/wallet/screen/PickWalletMnemonicScreen/PickWalletMnemonicScreen.tsx
> +    const handleSkip = async () => {
el `async` no hace falta si no hay codigo asincrono en la funcion

2024-03-25 08:23 UTC, JordiParraCrespo commented on src/locale/locales/en/common.json
> +    "IWillDoItLater": "I’ll do it later"
Tmb hacen falta los otros locales

2024-03-25 10:38 UTC, silvap-javier commented on src/module/wallet/component/core/WalletsBackupModal/WalletPrivateKeyBackup/WalletPrivateKeyBackup.tsx
> +                WalletStorage.setIsBackupDone(true);
Done

2024-03-25 10:38 UTC, silvap-javier commented on src/module/wallet/navigator/CreateWalletNavigatorGroup.tsx
> +                            onNextScreen={() => handleTabChange(CreateWalletScreens.SET_WALLET_PIN)}
Ok

2024-03-25 10:38 UTC, silvap-javier commented on src/module/wallet/screen/PickWalletMnemonicScreen/PickWalletMnemonicScreen.tsx
> +    onNextScreen: () => void;
Ok

2024-03-25 10:38 UTC, silvap-javier commented on src/module/wallet/screen/PickWalletMnemonicScreen/PickWalletMnemonicScreen.tsx
> +    const handleSkip = async () => {
ok

2024-03-25 10:38 UTC, silvap-javier commented on src/locale/locales/en/common.json
> +    "IWillDoItLater": "I’ll do it later"
Done

2024-03-26 12:02 UTC, JordiParraCrespo approved these changes

2024-03-26 12:03 UTC, merged