[TA-2388] [APP] : Show backup callout when is not backup done and show NotificationIcon
Peersyst/near-mobile-wallet pull request #461
Opened 2024-03-21 17:07 UTC by silvap-javier

[TA-2388] [APP] : Show backup callout when is not backup done and show NotificationIcon
## Issues

closes #

## Dependencies

#457 #458 #460 

## Changes

- Add useIsBackupDone
- Add recover isBackupDone in useLoad
- Show Alert and NotificactionIcon when isBackupDone is false

2024-03-27 10:17 UTC, JordiParraCrespo requested changes

2024-03-27 10:17 UTC, JordiParraCrespo commented on src/locale/locales/en/common.json
> +    "backup_wallet_advise_text_2_text_2": "If someone has asked you for your mnemonic or private key, they likely only want to steal your account",
Faltan locales y habría que mejorar el naming `backup_wallet_advise_text_2_text` `backup_wallet_advise_text_2_text_2`

2024-03-27 10:17 UTC, JordiParraCrespo commented on src/module/common/component/navigation/Header/Header.tsx
> +    const isBackupDone = useIsBackupDone();
Muy bien el hook! :smile: Haria un hook de `useHasNotifications` que de momento devuelva el resultado de `useIsBackupDone`. Así si luego hay que añadir más posibilidades ya está hecho

2024-03-27 10:17 UTC, JordiParraCrespo commented on src/module/settings/components/navigation/SettingsMenuItemWithAlert/SettingsMenuItemWithAlert.tsx
> +const SettingsMenuItemWithAlert = ({ text, onPress, destructive = false, children }: SettingsMenuItemWithAlertProps): JSX.Element => (
Vigilar el naming :warning: Es raro el naming esto no lleva Alert. 
Por otro lado este componente esta duplicado no? Deberías añadir la prop de Children a `SettingsMenuItem` y con eso debería bastar. 
Muy bien la prop de destructive! :smile:

2024-03-27 10:17 UTC, JordiParraCrespo commented on src/module/settings/hook/useIsBackupDone.ts
> +        const checkNotifications = async () => {
Esta función y `useEffect` es dummy :warning: :warning: :warning: 
Siempre está bien hacer un autoreview para detectar cosas más rápidas como estas :+1:

2024-03-27 10:17 UTC, JordiParraCrespo commented on src/locale/locales/en/common.json
> +    "notBackup": "Important! You have not done yet",
Intenta usar keys del locale más descriptivas. 
Por ejemplo: `notBackup` -> `youHaveNotDoneBackupYet`

2024-03-27 13:27 UTC, JordiParraCrespo requested changes
Último cambios y revisa el merge que ha habido lio

2024-03-27 13:27 UTC, JordiParraCrespo commented on src/module/settings/components/navigation/SettingsMenuItem/SettingsMenuItem.tsx
> +        <View style={style}>
Esto puede ser una `Col` siempre

2024-03-27 13:27 UTC, JordiParraCrespo commented on src/module/settings/components/navigation/SettingsMenuItem/SettingsMenuItem.tsx
> +const SettingsMenuItem = ({ text, children, onPress, style, destructive = false }: SettingsMenuItemProps): JSX.Element => (
El style deber ir para el `SettingsTouchableCard`

2024-03-27 13:27 UTC, JordiParraCrespo commented on src/module/nft/component/display/NftImage/NftImage.styles.ts
> -    objectFit: "cover",
mmm seguro q qieres borrar esto?

2024-03-27 13:40 UTC, silvap-javier commented on src/module/settings/components/navigation/SettingsMenuItem/SettingsMenuItem.tsx
> +        <View style={style}>
ok

2024-03-27 13:40 UTC, silvap-javier commented on src/module/settings/components/navigation/SettingsMenuItem/SettingsMenuItem.tsx
> +const SettingsMenuItem = ({ text, children, onPress, style, destructive = false }: SettingsMenuItemProps): JSX.Element => (
ok

2024-03-27 13:41 UTC, silvap-javier commented on src/module/nft/component/display/NftImage/NftImage.styles.ts
> -    objectFit: "cover",
No lo borre, el merge la lio

2024-03-28 11:52 UTC, JordiParraCrespo approved these changes

2024-03-28 12:39 UTC, merged