[TA-2390] [App] feat : redesign activity empty state
Peersyst/near-mobile-wallet pull request #464
Opened 2024-03-25 16:17 UTC by silvap-javier

[TA-2390][App] feat : redesign activity empty state

## Issues

closes #

## Dependencies

#461 #462 

## Changes

- Add OnBoardingActionsList component

2024-03-27 14:15 UTC, JordiParraCrespo requested changes
Bien!!

2024-03-27 14:15 UTC, JordiParraCrespo commented on src/locale/locales/es/common.json
> +    "theresNotTransactionsYetMeanwhileYouCan": "Aún no hay transacciones. Mientras tanto, puedes",
Quizá son demasiado largas las localeKeys qué te parecen estas? 
```
noTransactionsText
addNearCallToActionText
backupWallet
backupWalletCallToActionText
```

2024-03-27 14:15 UTC, JordiParraCrespo commented on src/module/common/component/feedback/OnBoardingActionsList/OnBoardingActionsList.tsx
> +const OnBoardingActionsList = () => {
Return type =)

2024-03-27 14:15 UTC, JordiParraCrespo commented on src/module/common/component/feedback/OnBoardingActionsList/OnBoardingActionsList.tsx
> +            <Typography variant="body3Strong" numberOfLines={2} textAlign="center" style={{ width: "60%" }}>
Yo haria que sea scrolleable más que añadir `numberOfLines={2}` no?

2024-03-27 14:15 UTC, JordiParraCrespo commented on src/module/common/component/feedback/OnBoardingActionsList/OnBoardingActionsList.tsx
> +            {!isBackupDone && (
Bien!

2024-03-27 14:15 UTC, JordiParraCrespo commented on src/module/transaction/component/feedback/EmptyActionsList/EmptyActionsList.tsx
> -    return <EmptyListComponent title={translateError("no_transactions")} text={translate("start_making_transactions")} />;
Hay que revisar de borrar las `localeKeys` que ya no se usan xq se han ido borrando!

2024-03-27 15:13 UTC, silvap-javier commented
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/63ddca03-aebc-49ed-a6e2-7f6672915fcc)

2024-03-28 12:54 UTC, JordiParraCrespo commented on src/module/common/component/feedback/OnBoardingActionsList/OnBoardingActionsList.tsx
> +    const {
`useIsBackupDone`

2024-03-28 12:57 UTC, JordiParraCrespo requested changes

2024-04-01 18:00 UTC, silvap-javier commented on src/locale/locales/en/common.json
> +    "andThisYouWillBeAbleToRecoverYourWalletWhenYouNeedItWithoutLosingYourNear": "and this you will be able to recover your wallet when you need it without losing your NEAR"
Done

2024-04-01 18:00 UTC, silvap-javier commented on src/module/common/component/feedback/OnBoardingActionsList/OnBoardingActionsList.tsx
> +    const {
Done

2024-04-03 09:25 UTC, JordiParraCrespo commented
Revisar UI que te he pasado x el chat

2024-04-03 09:26 UTC, JordiParraCrespo commented
Revisar si has borrado más locales que no se usen!   CTRL + shift + f

2024-04-04 07:36 UTC, JordiParraCrespo approved these changes

2024-04-04 07:46 UTC, JordiParraCrespo approved these changes

2024-04-04 07:57 UTC, merged