[TA-2392] [APP] feat : OutOfNear component
Peersyst/near-mobile-wallet pull request #467
Opened 2024-03-26 17:32 UTC by silvap-javier

[TA-2392] [APP] feat : OutOfNear component
## Issues

closes #

## Dependencies

#465 

## Changes

- Add YouDontHaveNearCard component

2024-03-27 14:18 UTC, JordiParraCrespo requested changes
Muy bien esta pr!! Mucho mejor los detallitos!! :top: :mechanical_arm:

2024-03-27 14:18 UTC, JordiParraCrespo commented on src/locale/locales/en/common.json
> +    "youHave0NEAR": "You have 0 NEAR",
Guay las `localeKeys` :smile:

2024-03-27 14:18 UTC, JordiParraCrespo commented on src/module/nft/component/core/NftDetailsModal/NftDetailsModalContent/NftDetailsModalContent.styles.ts
> +    height: dimensions.width - CARD_MODAL_PADDING * 8,
Xq x 8?

2024-03-27 14:18 UTC, JordiParraCrespo commented on src/module/wallet/component/display/YouDontHaveNearCard/YouDontHaveNearCard.styles.ts
> +    color: theme.palette.mode === "dark" ? theme.palette.text : alpha(theme.palette.gray[900], 0.6),
Aquí has de seleccionar el `overlay` `palette.overlay` o algo así

2024-03-27 14:18 UTC, JordiParraCrespo commented on src/module/wallet/component/display/YouDontHaveNearCard/YouDontHaveNearCard.tsx
> +            <Button variant="primary" onPress={() => navigate.navigate(MainScreens.FIAT_ORDERS)}>
Esto funciona okey?

2024-03-28 12:42 UTC, JordiParraCrespo requested changes

2024-03-28 12:42 UTC, JordiParraCrespo commented on src/module/nft/component/core/NftDetailsModal/NftDetailsModalContent/NftDetailsModalContent.styles.ts
> +    objectFit: "contain",
Xq `contain` y no `cover` ?

2024-03-28 12:42 UTC, JordiParraCrespo commented on src/module/nft/component/core/NftDetailsModal/NftDetailsModalContent/NftDetailsModalContent.styles.ts
> +    height: dimensions.width - CARD_MODAL_PADDING * 8,
hablalo con ferran a ver como ha de ser esto

2024-03-28 12:42 UTC, JordiParraCrespo commented on src/module/wallet/component/display/YouDontHaveNearCard/YouDontHaveNearCard.styles.ts
> +    color: theme.palette.mode === "dark" ? theme.palette.text : alpha(theme.palette.gray[900], 0.6),
Aqi seria ` theme.palette.overlay["60%"]`

2024-03-28 13:01 UTC, JordiParraCrespo commented on src/module/nft/component/core/NftDetailsModal/NftDetailsModalContent/NftDetailsModalContent.styles.ts
> +    height: dimensions.width - CARD_MODAL_PADDING * 8,
![image](https://github.com/Peersyst/near-mobile-wallet/assets/52425638/d1060b95-0f95-4b47-b086-8a13653b37e4)
Scrolleable + dejamos fullwidth =)

2024-04-01 18:11 UTC, silvap-javier commented on src/module/nft/component/core/NftDetailsModal/NftDetailsModalContent/NftDetailsModalContent.styles.ts
> +    objectFit: "contain",
Done

2024-04-01 18:11 UTC, silvap-javier commented on src/module/wallet/component/display/YouDontHaveNearCard/YouDontHaveNearCard.styles.ts
> +    color: theme.palette.mode === "dark" ? theme.palette.text : alpha(theme.palette.gray[900], 0.6),
Done

2024-04-03 08:02 UTC, JordiParraCrespo approved these changes

2024-04-03 08:02 UTC, merged