[TA-2397] [App] feat : create out of near validator in token detail modal
Peersyst/near-mobile-wallet pull request #468
Opened 2024-03-26 18:39 UTC by silvap-javier

[TA-2397] [App] feat : create out of near validator in token detail modal

## Issues

closes #

## Dependencies

#467 

## Changes

-

2024-03-28 12:26 UTC, JordiParraCrespo requested changes

2024-03-28 12:26 UTC, JordiParraCrespo commented on src/module/common/hook/useHaveNearInAccount.ts
> +    useEffect(() => {
Esto es una mala practica :warning:
React ya se encarga d rerenderizar los valores no hace falta el `useEffect`.
```
const hasNearInAccount = !isLoading && available !== 0;
```

2024-03-28 12:26 UTC, JordiParraCrespo commented on src/module/common/hook/useHaveNearInAccount.ts
> +export default function useHaveNearInAccount(): boolean {
Aquí seria `has` en vez de `have` no ? Xq hace referencia al user

2024-03-28 12:28 UTC, JordiParraCrespo commented on src/module/common/hook/useHaveNearInAccount.ts
> +export default function useHaveNearInAccount(): boolean {
A bueno luego he visto que tienes `YouDontHaveNear` mm bueno como veas

2024-04-01 18:13 UTC, silvap-javier commented on src/module/common/hook/useHaveNearInAccount.ts
> +export default function useHaveNearInAccount(): boolean {
lo dejamos con have :)

2024-04-01 18:16 UTC, silvap-javier commented on src/module/common/hook/useHaveNearInAccount.ts
> +    useEffect(() => {
True

2024-04-03 08:44 UTC, merged