[TA-2366] [APP] feat : Faqs expandable
Peersyst/near-mobile-wallet pull request #470
Opened 2024-03-27 20:06 UTC by silvap-javier

[TA-2366] [APP] feat : Faqs expandable
## Issues

closes #

## Dependencies

#

## Changes

- Add FAQ component and Expandable.stylesheet

2024-03-28 12:38 UTC, JordiParraCrespo requested changes

2024-03-28 12:38 UTC, JordiParraCrespo commented on package.json
> +        "@swisstype/react": "^0.0.2",
Esto es una dev dependency. `Typescript` solo es para el desarrollo :+1:

2024-03-28 12:38 UTC, JordiParraCrespo commented on src/stylesheets/Expandable.stylesheet.ts
> +    borderColor: "#26262614",
Esto entonces no cambiará para light y dark xq no puedess acceder al theme?

2024-04-03 14:14 UTC, silvap-javier commented on package.json
> +        "@swisstype/react": "^0.0.2",
Done

2024-04-03 14:14 UTC, silvap-javier commented on src/stylesheets/Expandable.stylesheet.ts
> +    borderColor: "#26262614",
Donme

2024-04-04 08:43 UTC, JordiParraCrespo approved these changes

2024-04-04 08:44 UTC, merged