[TA-2370] [TA-2368] [TA-2367] [APP] feat: faqs page
Peersyst/near-mobile-wallet pull request #475
Opened 2024-04-02 17:24 UTC by silvap-javier

[TA-2370] [TA-2368] [TA-2367] [APP] feat: faqs page

## Issues

closes #

## Dependencies

#

## Changes

- Add FAQs Page
- Add Icon Help in Header

2024-04-03 11:43 UTC, JordiParraCrespo requested changes

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/locale/locales/en/faqs.json
> +    "aboutTheNearWalletApp": {
No haria falta esta primera key no?

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/common/component/navigation/TransExternalLink/TransExternalLink.tsx
> +function TransExternalLink({ children, ...rest }: TransExternalLinkProps): JSX.Element {
Q es `TransExternalLink` ?

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/common/component/surface/Card/Card.styles.ts
> +    ...(variant === "white" && {
en dark mode no sera white

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/common/component/surface/Card/Card.tsx
> +    variant?: "gray" | "blue" | "white";
Revisar

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/common/component/navigation/Header/Header.tsx
> +                <HeaderSettingsButton right={40} onPress={() => navigation.navigate(MainScreens.FAQS)}>
Mejor haz una Row que encuadre a los dos y que sea ella quien se coloca que no posicionar a los dos.

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/faqs/component/display/FAQs/FAQs.styles.ts
> +export const FAQsRoot = styled(Card)(() => ({
Guay!

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/common/component/surface/Card/Card.tsx
> +    variant?: "gray" | "blue" | "white";
X mi seria `gray` | `blue` | `default`  y que default coga el background!. 
Tmb haria q x defecto te ponga el background default x lo q habrá q ajustar dnde no se haya pasado xq el defaul de antes era gray

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/faqs/component/display/FAQs/FAQs.tsx
> +                                <Typography variant="body2Strong">{translateFAQ(`${key as keyof ResourceType["faqs"]}.label`)}</Typography>
Xq especificas la label con una Typografia y no directamente?

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/faqs/component/display/FAQs/FAQs.tsx
> +const FAQs = memo(function FAQs() {
Si no tiene props no tiene sentido el memo, no?

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/faqs/component/display/FAQs/FAQs.tsx
> +            <ScrollView>
La ScrollView debería ser de toda la pantalla no?

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/faqs/component/display/FAQs/FAQs.tsx
> +                            key={key}
Bien la `key`! Xq el `alignItems` ?

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/faqs/component/display/FAQs/FAQs.tsx
> +                                                i18nKey={`faqs:${key}.questions.${questionIndex}.answer` as any}
No entiendo esto

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/faqs/component/display/FAQs/FAQs.tsx
> +                                        question={translateFAQ(`${key}.questions.${questionIndex}.question` as any)}
No hay que usar el `any` deberías intentar tiparlo

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/main/component/layout/BaseMainScreen/BaseMainScreen.styles.ts
> +    backgroundColor: variant === BaseMainVariant.WHITE ? theme.palette.background : theme.palette.overlay["4%"],
Fijate en la `SettingsScreen`.
Recuerda tmb que la app no es white ni dark ya que tiene dark mode

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/faqs/screen/FaqsScreen.tsx
> +        <BaseMainScreen variant={BaseMainVariant.GRAY}>
BaseSecondaryScreen creo q tendría que ser

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/main/component/layout/BaseMainScreen/BaseMainScreen.tsx
> +const BaseMainScreen = ({ children, variant = BaseMainVariant.WHITE, ...navbarProps }: BaseMainScreenProps): JSX.Element => {
Delete

2024-04-03 11:43 UTC, JordiParraCrespo commented on src/module/common/component/navigation/ExternalLink/ExternalLink.tsx
> +function ExternalLink({ to, children = "", color = "primary", ...typographyProps }: ExternalLinkProps): JSX.Element {
Muy bien el componente! =)

2024-04-03 15:50 UTC, silvap-javier commented on src/module/common/component/navigation/TransExternalLink/TransExternalLink.tsx
> +function TransExternalLink({ children, ...rest }: TransExternalLinkProps): JSX.Element {
Esta bueno, si tiene una etiqueta <a> en el translate, lo crea al link

2024-04-03 16:51 UTC, silvap-javier commented on src/module/faqs/component/display/FAQs/FAQs.tsx
> +const FAQs = memo(function FAQs() {
vale

2024-04-03 16:51 UTC, silvap-javier commented on src/module/faqs/component/display/FAQs/FAQs.tsx
> +            <ScrollView>
Vale

2024-04-03 16:51 UTC, silvap-javier commented on src/module/faqs/component/display/FAQs/FAQs.tsx
> +                            key={key}
El alignItems xq sino no se renderiza bien, lo vi de CBCD y es necesario

2024-04-03 16:51 UTC, silvap-javier commented on src/module/faqs/component/display/FAQs/FAQs.tsx
> +                                <Typography variant="body2Strong">{translateFAQ(`${key as keyof ResourceType["faqs"]}.label`)}</Typography>
Lo he puesto, por que no lo toma, lo he revisado, y creo que en el labelStylesheet lo define, y no lo logre pisar con el variant.

2024-04-03 16:51 UTC, silvap-javier commented on src/module/faqs/screen/FaqsScreen.tsx
> +        <BaseMainScreen variant={BaseMainVariant.GRAY}>
No, fijate que es distinto, o por lo menos en el diseño, en secondary, no muestra el header, y para las faqs en el diseño esta el header

2024-04-03 16:51 UTC, silvap-javier commented on src/module/faqs/screen/FaqsScreen.tsx
> +        <BaseMainScreen variant={BaseMainVariant.GRAY}>
![image](https://github.com/Peersyst/near-mobile-wallet/assets/2675924/9d38c3e9-15e5-4399-921c-d973e4eabab1)

2024-04-03 16:51 UTC, silvap-javier commented on src/module/main/component/layout/BaseMainScreen/BaseMainScreen.styles.ts
> +    backgroundColor: variant === BaseMainVariant.WHITE ? theme.palette.background : theme.palette.overlay["4%"],
True, lo cambie por default

2024-04-03 16:51 UTC, silvap-javier commented on src/module/common/component/navigation/Header/Header.tsx
> +                <HeaderSettingsButton right={40} onPress={() => navigation.navigate(MainScreens.FAQS)}>
Done

2024-04-03 16:52 UTC, silvap-javier commented on src/locale/locales/en/faqs.json
> +    "aboutTheNearWalletApp": {
No, pero me gustaria dejarlo asi, por si agregamos mas cosas, como en CBCD

2024-04-04 11:50 UTC, JordiParraCrespo approved these changes

2024-04-04 12:26 UTC, merged