[TA-2508] [APP] feat : Add token descriptions
Peersyst/near-mobile-wallet pull request #485
Opened 2024-04-08 12:30 UTC by silvap-javier

[TA-2508] [APP] feat : Add token descriptions

## Issues

closes #

## Dependencies

#

## Changes

-

2024-04-08 12:46 UTC, JordiParraCrespo requested changes

2024-04-08 12:46 UTC, JordiParraCrespo commented on src/locale/locales/en/en.ts
> +    tokens: tokens,
Bien!!!!!!!!!!!!!!!!!!!!
Me gusta

2024-04-08 12:46 UTC, JordiParraCrespo commented on src/module/token/component/core/TokenDetailsModal/TokenDetailsModalContent.tsx
> +            {token.metadata?.symbol && (
Aquí deberíamos mirar si tenemos la traducción y si no la tenemos no renderizar la Typography :)

2024-04-08 15:43 UTC, silvap-javier commented on src/module/token/component/core/TokenDetailsModal/TokenDetailsModalContent.tsx
> +            {token.metadata?.symbol && (
Done

2024-04-09 07:40 UTC, JordiParraCrespo approved these changes

2024-04-09 07:58 UTC, merged