[TA-2404] [TA-2403] [App] feat :  add expo updates in app
Peersyst/near-mobile-wallet pull request #489
Opened 2024-04-10 16:42 UTC by silvap-javier

[TA-2404] [TA-2403] [App] feat :  add expo updates in app

## Issues

closes #

## Dependencies

#

## Changes

-

2024-04-11 13:57 UTC, JordiParraCrespo requested changes

2024-04-11 13:57 UTC, JordiParraCrespo commented on src/module/common/component/feedback/UpdateApp/UpdateApp.tsx
> +        <ThemeOverrideProvider>
Xq añades el `ThemeOverrideProvider` ?

2024-04-11 13:57 UTC, JordiParraCrespo commented on src/module/common/component/feedback/UpdatingAppModal/UpdatingAppModal.tsx
> +export function UpdatingAppModal({ open }: UpdatingAppModalProps): JSX.Element {
Xq no has actualizado el `LoadingModal` ?

2024-04-11 13:58 UTC, JordiParraCrespo commented on src/module/common/component/feedback/UpdateApp/UpdateApp.tsx
> +export function UpdateApp(): JSX.Element {
Quizá le diria `AppUpdater` ?

2024-04-11 15:29 UTC, silvap-javier commented on src/module/common/component/feedback/UpdateApp/UpdateApp.tsx
> +export function UpdateApp(): JSX.Element {
ok

2024-04-11 15:29 UTC, silvap-javier commented on src/module/common/component/feedback/UpdateApp/UpdateApp.tsx
> +        <ThemeOverrideProvider>
Para que tenga el teme el modal, pero nada ahi lo removi

2024-04-11 15:29 UTC, silvap-javier commented on src/module/common/component/feedback/UpdatingAppModal/UpdatingAppModal.tsx
> +export function UpdatingAppModal({ open }: UpdatingAppModalProps): JSX.Element {
Por que es bastante diferente los estilos, en cbcd esta igual, hay uno de loading y otro para el updating

2024-04-12 13:02 UTC, JordiParraCrespo requested changes
Super lo del `LoadingModal`! Te dejo algunas cosas más que he visto que ahora si q me lo he podido mirar con más calma

2024-04-12 13:02 UTC, JordiParraCrespo commented on src/module/common/component/feedback/UpdateRequiredModal/UpdateRequiredModal.tsx
> +        hideModal(UpdateRequiredModal.id);
Ahora que lo he revisado cuando falla se queda en el estado de loading. Debería ir al status de error el `LoadingModal` no??? I igual con un botón que te lleve a actualizar a las stores...

2024-04-12 13:02 UTC, JordiParraCrespo commented on src/module/common/component/feedback/UpdatingAppModal/UpdatingAppModal.tsx
> +            processingDescriptionMessage={translate("pleaseWaitAMoment")}
Este mensaje lo pondría siempre no?

2024-04-15 09:12 UTC, silvap-javier commented on src/module/common/component/feedback/UpdateRequiredModal/UpdateRequiredModal.tsx
> +        hideModal(UpdateRequiredModal.id);
Done

2024-04-15 09:27 UTC, JordiParraCrespo approved these changes

2024-04-15 09:39 UTC, merged