[APP] fixs: resolved wrong add deposits
Peersyst/near-mobile-wallet pull request #503
Opened 2024-04-26 14:20 UTC by silvap-javier

[APP] fixs: resolved wrong add deposits

## Issues

closes #

## Dependencies

#

## Changes

-

2024-04-30 11:03 UTC, JordiParraCrespo requested changes

2024-04-30 11:03 UTC, JordiParraCrespo commented on src/module/sdk/NearApiService/NearBlocks/NearBlocksService.ts
> -                                }),
Yo haria que si no existe se siga pasando undefined. Ya qque si se pasa "0" quiza en algun sitio sale cero y no deberia de salir o asi.

2024-04-30 11:03 UTC, JordiParraCrespo commented on src/module/sdk/NearApiService/NearBlocks/NearBlocksService.ts
> +        const deposit = actions.reduce((acc: string, current: NearBlocksActionDto) => {
Creo que las transformaciones aqi dentro a bigint no son necesarias si todos los numeros son bigints. Me refiero a hacer `toString()` directamente.

```
const deposit = actions.reduce((acc: string, current: NearBlocksActionDto) => {
           return current.deposit ? addNearAmounts(BigInt(acc).toString(), BigInt(current.deposit).toString()) : acc;
}, BigInt(0).toString());
```

2024-05-01 11:21 UTC, silvap-javier commented on src/module/sdk/NearApiService/NearBlocks/NearBlocksService.ts
> +        const deposit = actions.reduce((acc: string, current: NearBlocksActionDto) => {
Done

2024-05-01 11:46 UTC, silvap-javier commented on src/module/sdk/NearApiService/NearBlocks/NearBlocksService.ts
> -                                }),
Done

2024-05-01 11:46 UTC, silvap-javier commented on src/module/sdk/NearApiService/NearBlocks/NearBlocksService.ts
> +        if (!actions) return convertYoctoToNear(BigInt(0).toString());
Done

2024-05-06 14:55 UTC, AgustinMJ approved these changes

2024-05-06 14:57 UTC, merged