[TA-3028] : Export private key quiz
Peersyst/near-mobile-wallet pull request #520
Opened 2024-07-18 19:03 UTC by silvap-javier

Export private key quiz

## Issues

closes #

## Dependencies

#

## Changes

-

2024-07-19 07:57 UTC, AgustinMJ requested changes

2024-07-19 07:57 UTC, AgustinMJ commented on src/locale/locales/en/quiz.json
> +    "aPasswordForYourEmailAddress": "A password for your email address"
Creo que hay alguna traducción que no se usa, porque hay más de tres respuestas por pregunta, si puedes mirar cuales són las que sobran y ordenarlo bien para tener la traducción de la pregunta y las traducciones de las respuestas seguidas en todos los locales 🙏🏼

2024-07-19 07:57 UTC, AgustinMJ commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/WalletQuizBackup.tsx
> +        setError("");
Mejor que sea `undefined` si no hay error

2024-07-19 07:57 UTC, AgustinMJ commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/WalletQuizBackup.tsx
> +                        key={currentQuestionIndex}
No debería de hacer falta esta `key`

2024-07-19 07:57 UTC, AgustinMJ commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/steps/WalletQuizBackupQuiz.tsx
> +                                    <RadioButton
Habría que mirar que no se corten las respuestas

![Screenshot 2024-07-19 at 09 52 13](https://github.com/user-attachments/assets/959273ee-5f29-4c2c-b014-ae7618a694d7)

2024-07-19 07:57 UTC, AgustinMJ commented on src/module/common/component/navigation/CardNavigatorModal/CardNavigatorModal.tsx
> +    index?: number;
Esto no es correcto, si hiciera falta en el styled component de `WalletsBackupModalRoot`habría que ponerlo en sus props del `styled`. Igualmente, ya hemos visto que no hará falta

2024-07-23 07:54 UTC, JordiParraCrespo requested changes
Buen trabajo!!

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/config/config.declarations.d.ts
> +    response: string[];
responses* Que asi se entiende mas. Tmb sino answers

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/WalletQuizBackup.tsx
> +        const shuffledQuestions = [...config.securityQuizList].sort(() => 0.5 - Math.random());
Mola!! :)) Podrias hacer una funcion que fuera`randomSort`

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/WalletQuizBackup.tsx
> +        const originalShuffledQuestions = shuffledQuestions.slice(0, 3);
Podria ir en la config el numero de preguntas :)

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/WalletQuizBackup.tsx
> +        setQuizQuestionsShuffled(shuffledQuestionsWithShuffledResponses);
No es necesario este useEffect inicial. Es mejor practica inicializar el useState directamente
https://dev.to/nibble/lazy-state-initialization-in-functional-components-1ib0

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/WalletQuizBackup.tsx
> +        const updatedAnswers = [...answers];
Creo q no es necesario crear un nuevo array no?

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/WalletQuizBackup.tsx
> +        setAnswers(updatedAnswers);
Tmb podrias hacer algo asi

setAnswers((answers) => {
    answers[currentQuestionIndex] = value;
    return answers;
    }
});

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/steps/WalletQuizBackupLayout.tsx
> +                <Col flex={1} style={{ justifyContent: "flex-end" }}>
Puedes pasarle el justifyContent sin el style asi tmpoco esta mal claro

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/steps/WalletQuizBackupWelcome.tsx
> +            <Col style={{ justifyContent: "center", alignItems: "center" }} flex={1} gap={40}>
Aqui tmb puedes pasarle los atributos sin el style

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/WalletQuizBackup.tsx
> +    return (
Esta super el quiz!!! Me molaria un custom hook y quede ahi toda la magia (sugerencia :) )

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/config/config.declarations.d.ts
> +    answer: string;
Quiza mejor `question` no?

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/locale/locales/en/quiz.json
> +    "whyShouldYouNeverShareYourMnemonic": "Why should you never share your mnemonic?",
Bien el namespace del locale :)

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/steps/WalletQuizBackupLayout.tsx
> +        <Col flex={1} gap={24}>
Bien la reusabilidad :)

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/locale/locales/es/quiz.json
> +    "aKeyUsedToEncryptMessages": "Una clave utilizada para encriptar mensajes",
Esta pregunta puede dar lugar a confusion ya que con una llave privada firmas mensajes. Si que es verdad que se encriptan con la publica pero aun asi se podria confundir con encriptar i firmar.

Podrias poner quiza:
`El identificador de mi cuenta que debo compartir para recibir tokens`

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/locale/locales/es/quiz.json
> +    "willVictorOrArnauFromOurSupportTeamAskForYourMnemonic": "¿Victor o Arnau de nuestro equipo de soporte te pedirán tu mnemónico?",
Esta casi q la pondria que saliera siempre la verdad jaja

2024-07-23 07:54 UTC, JordiParraCrespo commented on src/locale/locales/es/quiz.json
> +    "willAnyoneFromNearMobileTeamAskForYourMnemonic": "¿Alguien del equipo de Near Mobile te pedirá tu mnemónico?",
Muy bien!

2024-07-24 09:38 UTC, silvap-javier commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/steps/WalletQuizBackupQuiz.tsx
> +                                    <RadioButton
Done

2024-07-24 09:38 UTC, silvap-javier commented on src/module/wallet/component/core/WalletsBackupModal/WalletsBackupModal.styles.ts
> +    minHeight: index === WalletsBackupModalTabs.QUIZ ? dimensions.height * 0.5 : dimensions.height * 0.85,
Done

2024-07-24 09:38 UTC, silvap-javier commented on src/module/common/component/navigation/CardNavigatorModal/CardNavigatorModal.tsx
> +    index?: number;
Revolved

2024-07-24 09:40 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/WalletQuizBackup.tsx
> +        const updatedAnswers = [...answers];
Xo xq hace falta copiarlo?

2024-07-24 09:41 UTC, JordiParraCrespo commented on src/module/wallet/component/core/WalletsBackupModal/WalletQuizBackup/WalletQuizBackup.tsx
> +        setError("");
:eye:

2024-07-24 09:44 UTC, silvap-javier commented on src/locale/locales/es/quiz.json
> +    "aKeyUsedToEncryptMessages": "Una clave utilizada para encriptar mensajes",
El victor dijo que estaba ok, si quires luego repasamos de nuievo todas

2024-07-24 09:46 UTC, JordiParraCrespo commented on src/module/common/component/navigation/CardNavigatorModal/CardNavigatorModal.tsx
> +    index?: number;
El index no se usa no?

2024-07-24 11:07 UTC, JordiParraCrespo approved these changes

2024-07-24 11:09 UTC, merged