Update posthog events
Peersyst/near-mobile-wallet pull request #561
Opened 2024-11-13 12:36 UTC by JordiParraCrespo

2024-11-13 13:25 UTC, JordiParraCrespo commented
DO NOT MERGE YET

2024-11-15 08:59 UTC, AgustinMJ requested changes

2024-11-15 08:59 UTC, AgustinMJ commented on src/module/analytics/hooks/useCapture.ts
> +    }, [state.wallets]);
Ficaria `state.wallets.length` per assegurar que la referència de `wallets` no canvia i provoca més execucions

2024-11-15 11:41 UTC, JordiParraCrespo commented on src/module/analytics/hooks/useCapture.ts
> +    }, [state.wallets]);
donete

2024-11-15 11:44 UTC, merged