TX List
Peersyst/near-mobile-wallet pull request #68
Opened 2022-09-30 09:33 UTC by JordiParraCrespo

# TX List
## Issues
- closes #9 
## PR deps
- depens #64 
## Changes
- TX List
- TX Card
- TX DetailsModal

2022-10-03 07:53 UTC, AgustinMJ requested changes

2022-10-03 07:53 UTC, AgustinMJ commented on src/module/transaction/component/core/TransactionDetailsModal/TransactionDetailsHeader.tsx
> +                {showAmount && <TransactionAmount variant="body1Strong" type={type} balance={amount} units={token ?? tokenName} />}
Aquí no seria `token ?? "token"`? Ja agafa el config.tokenName el Balance

2022-10-03 07:53 UTC, AgustinMJ commented on src/module/transaction/component/display/TransactionAmount/TransactionAmount.tsx
> +    const { action, primary } = getTransactionAmountUtils(type) || {};
Se'm fa una mica raro el getTransactionAmountUtils, crec que abans tenia més sentit el transactionTypeToBalanceAction. No crec que aquesta funció hagi de retornar el color del Balance, ja que hauria de ser algo aliè a la ui. Crec que estaria millor deixar-ho com abans i fer:
````ts
const action = transactionTypeToBalanceAction(type);
const isPrimary = action === "add";
````
I en el Balance fer: `color={(palette) => palette[isPrimary ? "primary" : "text"]}`

2022-10-03 07:53 UTC, AgustinMJ commented on src/module/transaction/component/display/TransactionCard/TransactionCard.styles.ts
> +    marginBottom: last ? 25 : 0,
Això ja no fa falta entenc

2022-10-03 07:53 UTC, AgustinMJ commented on src/module/transaction/component/display/TransactionCard/TransactionCard.styles.ts
>      paddingVertical: 14,
Segons els dissenys aquest padding és 16, potser queda massa gran i 14 ja està bé? Com ho veus amb 16?

2022-10-03 07:53 UTC, AgustinMJ commented on src/module/transaction/component/display/TransactionCard/TransactionCard.styles.ts
> -}));
També aprofitaria a posar aquest paddingVertical a la MainListCardRoot (millor que sigui la MainListCard que és el component que s'hauria d'utilitzar en teoria), ja que és comú a totes les cards de la app

2022-10-03 07:53 UTC, AgustinMJ commented on src/module/transaction/component/display/TransactionCard/TransactionCard.tsx
> +    const { timestamp, amount, type, token = tokenName, status } = transaction;
Aquí el mateix d'abans amb el tokenName, no fa falta agafar la config perquè amb "token" el Balance ja utilitza el tokenName de la config

2022-10-03 07:53 UTC, AgustinMJ commented on src/module/transaction/component/display/TransactionIcon/TransactionIcon.styles.ts
> +export const TxIcon = styledWithAs(Icon)<TransactionIconCompponentProps>(({ theme: { palette: p }, active }) => ({
Cuidado amb el styledWithAs que no és gaire estable jajaja, per casos concrets es pot utilitzar pero ojo. Aquí esta bé jo crec

2022-10-03 07:53 UTC, AgustinMJ commented on src/module/transaction/component/display/TransactionIcon/utils/txIconUtils.ts
> +export const TX_ICON_UTILS: Partial<Record<TransactionType, TxIconUtils>> = {
Potser TX_ICON a secas millor, TX_ICON_UTILS sona a col·lecció de utils. AIxò només és com un enum

2022-10-03 07:53 UTC, AgustinMJ commented on src/module/transaction/component/display/TransactionLabel/TransactionLabel.tsx
> +import { TX_LABEL } from "./utils/TX_LABEL";
Aquí com a txIcon millor que el nom de l'arxiu sigui txLabel, ja que sempre posem els noms en camelCase

2022-10-03 07:53 UTC, AgustinMJ commented on src/module/transaction/component/display/TransactionLabel/utils/TX_LABEL.ts
> +    [TransactionType.SEND_NFT]: "sent_nft",
Entenc que a partir d'aquí s'hauran de canviar quan tinguem el sdk nou, no?

2022-10-03 07:53 UTC, AgustinMJ commented on src/module/transaction/component/display/TransactionLabel/TransactionLabel.tsx
> +    accountId?: string;
Aquí podem fer un trickshot bastant guapo per mostrar la address si no hi ha accountId, que pot passar. Podem fer això:
````ts
export interface TransactionLabelProps = Omit<TypographyProps, "children"> & { type: FullTransaction["type"] } & ({ accountId: string } | { address: string })
````
Crec que així funcionarà, sempre t'obligarà a passar-li una de les dos, potser a sota tens algun problema per extreure la accountId o address, si vols ho podem fer junts això

2022-10-03 07:53 UTC, AgustinMJ commented on src/locale/i18n.types.ts
> +export type TransaltionResourceType = keyof ResourceType["translation"];
Això què fa?

2022-10-03 08:51 UTC, JordiParraCrespo commented on src/config/globalStyles.ts
> +const globalStyles: CreateGlobalStyles = ({ theme: { palette: p, typography } }) => ({
Okey!! pero ens els styled comp si q ho veig bé ficar p q es més ràpid jeje

2022-10-03 08:53 UTC, JordiParraCrespo commented on src/locale/locales/es/common.json
> +    "stake_added": "Added stake",
Bueno fico Stake añadido haha si no ja ens diran!

2022-10-03 08:53 UTC, JordiParraCrespo commented on src/module/common/component/display/PinDisplay/PinDisplay.tsx
> +                <Typography variant="body2Strong" color={(palette) => palette.white}>
Ups yes! Ho deixo en apla(palette.white, 0.6) ja que tant en light com en dark sha de veure igual =)

2022-10-03 08:55 UTC, JordiParraCrespo commented on src/module/common/component/navigation/BottomBar/BottomBarItem/BottomBarItem.styles.ts
> +    width: "22%",
Perq sigui més responsiu... Això bé de quan vaig probar la app amb el mobile de la meva mare que té el fontSize canviat.
Ficant-ho en % es veia bé tant en el meu mobile com en el seu

2022-10-03 09:03 UTC, JordiParraCrespo commented on src/module/main/component/display/MainList/MainList.tsx
> +            style={{ paddingHorizontal: "6%", paddingTop: 15 }}
Jolin bona!! =)

2022-10-03 09:04 UTC, JordiParraCrespo commented on src/module/sdk/core/transaction.service.ts
> +    SEND_NATIVE_TOKEN = "send_ckb",
Bueno de moment no... Però si hem de vigilar q no ens passi com a ckbull

2022-10-03 09:11 UTC, JordiParraCrespo commented on src/module/transaction/component/core/TransactionDetailsModal/TransactionDetailsBody/TransactionTypeDetails.tsx
>                              <Balance
done =) tot i q aquest component anirà fora segurament quan integrem amb el sdk de near

2022-10-03 09:12 UTC, JordiParraCrespo commented on src/module/transaction/component/core/TransactionDetailsModal/TransactionDetailsHeader.tsx
> +                {showAmount && <TransactionAmount variant="body1Strong" type={type} balance={amount} units={token ?? tokenName} />}
true!!

2022-10-03 09:12 UTC, JordiParraCrespo commented on src/module/transaction/component/core/TransactionsList/TransactionsList.tsx
> +            renderItem={({ item: tx, index }) => <TransactionCard transaction={tx} last={index === data.length - 1} />}
removed =)

2022-10-03 09:14 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionAmount/TransactionAmount.tsx
> +export interface TransactionAmountProps extends Omit<BalanceProps, "action"> {
okey makey

2022-10-03 09:20 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionAmount/TransactionAmount.tsx
> +    const { action, primary } = getTransactionAmountUtils(type) || {};
done =)

2022-10-03 09:21 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionCard/TransactionCard.styles.ts
>      paddingVertical: 14,
Ho he canviat a height així es igual jeje

2022-10-03 09:27 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionCard/TransactionCard.styles.ts
>      paddingVertical: 14,
Bueno a minHeight q si x algun motiu fa overflow amb landroid es fica hidden

2022-10-03 09:33 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionCard/TransactionCard.styles.ts
>      paddingVertical: 14,
okaay se queda 16 jeje

2022-10-03 09:34 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionCard/TransactionCard.styles.ts
> -}));
Done papá

2022-10-03 09:35 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionCard/TransactionCard.tsx
> +    const { timestamp, amount, type, token = tokenName, status } = transaction;
true ais ais

2022-10-03 09:35 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionIcon/TransactionIcon.styles.ts
> +export const TxIcon = styledWithAs(Icon)<TransactionIconCompponentProps>(({ theme: { palette: p }, active }) => ({
Okey tomaremos precauciones pero mola el styledWithAs jeje

2022-10-03 09:45 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionIcon/TransactionIcon.types.ts
> +    active?: boolean;
Si? Bueno ho sigui crec q relaciones més que es posa blau amb active que amb receive, no?

2022-10-03 09:58 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionIcon/utils/txIconUtils.ts
> +export const TX_ICON_UTILS: Partial<Record<TransactionType, TxIconUtils>> = {
done jeje

2022-10-03 10:01 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionLabel/TransactionLabel.tsx
> +import { TX_LABEL } from "./utils/TX_LABEL";
done jeje

2022-10-03 10:02 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionLabel/utils/TX_LABEL.ts
> +    [TransactionType.SEND_NFT]: "sent_nft",
sep de moment x deixarho el més fàcil x quan canviem el sdk

2022-10-03 10:09 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionLabel/TransactionLabel.tsx
> +    accountId?: string;
Bueno crec q maybe millor fer un component d'això que li pasis la account, detecti si es una named account o una implicit account (address)

2022-10-03 10:12 UTC, JordiParraCrespo commented on src/module/transaction/component/display/TransactionLabel/TransactionLabel.tsx
> +    accountId?: string;
O sigui sempre hi haurà una account, ja sigui implicita (address de tota la vida) o named (agustin.near). Realment no cal tractarles per separat, ja que el component de blockchain address ja s'encarrega de tot.

2022-10-03 10:30 UTC, JordiParraCrespo commented on src/locale/i18n.types.ts
> +export type TransaltionResourceType = keyof ResourceType["translation"];
El necessitava per tipar això jeje
Xq sino havia de fer un hook i ho volia fer un json amb les keys del locale per n
```
import { TransactionType } from "ckb-peersyst-sdk";
import { TransaltionResourceType } from "locale";

export const TX_LABEL: Record<Partial<TransactionType>, TransaltionResourceType> = {
    [TransactionType.SEND_NATIVE_TOKEN]: "sentTo",
    [TransactionType.SEND_TOKEN]: "sentTo",
    [TransactionType.RECEIVE_NATIVE_TOKEN]: "from",
    [TransactionType.RECEIVE_TOKEN]: "from",
    [TransactionType.SEND_NFT]: "sent_nft",
    [TransactionType.RECEIVE_NFT]: "received_nft",
    [TransactionType.SMART_CONTRACT_SEND]: "smart_contract",
    [TransactionType.SMART_CONTRACT_RECEIVE]: "received_nft",
    [TransactionType.STAKE]: "stake_added",
    [TransactionType.SMART_CONTRACT_RECEIVE]: "received_nft",
    [TransactionType.UNSTAKE]: "unstake",
    deposit_dao: "DAO_deposit",
    withdraw_dao: "DAO_withdrawal",
    unlock_dao: "unlock_DAO",
};

```

2022-10-04 10:28 UTC, AgustinMJ approved these changes

2022-10-04 10:33 UTC, merged