Redesign ReceiveModal
Peersyst/near-mobile-wallet pull request #83
Opened 2022-10-05 16:50 UTC by GuillemGarciaDev

# Redesign ReceiveModal

## Issues

closes #16 

## Changes

* ReceiveCard without use
* ReceiveModal gets all the logics
* ReceiveCard tests -> ReceiveModal tests
* New Container component located at "module/common/component/display/Container"
* ReceiveModal uses Container

2022-10-06 07:18 UTC, AgustinMJ requested changes
A mobile, la branch on fem el development és dev, per tant la pr hauria d'anar cap a dev, estava cap a main. No passa res, és per tenir-ho en compte per les próximes jeje.

Igualment, bona primera pr!! Has seguit bé l'estructura i has intentat fer-ho tot seguint la metodologia que hi ha dins del projecte que això ja costa😁

2022-10-06 07:18 UTC, AgustinMJ commented on src/module/transaction/component/core/ReceiveModal/ReceiveModal.tsx
> +    const closeModal = () => {
No esta malament això, però potser no fa falta definir una funció que només crida a una altra. Millor utilitzar el close directament jeje

2022-10-06 07:18 UTC, AgustinMJ commented on src/module/transaction/component/core/ReceiveModal/ReceiveModal.tsx
> +                <Typography textAlign="center" variant="body2">
Això t'ho trobaràs bastant en aquest primer stage de redesign de near-wallet. Com l'estem fent a partir de ckbull, encara estan les variants, colors i altres coses per tal de que no petés tot. Per això, moltes variants estan deprecated (a `typography.ts` ho pots veure, culpa meva que no t'ho vaig dir).

Per tant, esta bé cada cop que es fa el redesign d'una part, anar mirant en el figma quina de les noves variants és la que toca

2022-10-06 07:18 UTC, AgustinMJ commented on src/module/transaction/component/display/QRCode/QRCode.tsx
> +        <Row justifyContent="center" testID="QRCode" style={{ marginTop: 25 }}>
Oju amb els margins👀! Sempre s'han d'intentar evitar, sobre tot en components bàsics com pot ser el QRCode, ja que molts cops generen espai i pot costar molt veure d'on surt si més endavant s'ha de reajustar o canviar. No esta prohibit però, en algun cas especial sí que s'ha d'utilitzar el margin.

Doncs, la manera en que fem els espais és amb la prop de `gap` de les `Col`i `Row`. El 99% de les vegades ho fem amb això, així és el pare qui decideix la distribució dels fills i com es col·loquen.

Una altra opció, seria donar-li aquest marginTop des del pare amb un style. Però no des del propi QRCode, ja que potser s'utilitza a un altre lloc on no volem aquest marginTop. Finalment, potser aquí caldra fer-ho percentualment, ja que a una pantalla petita 25px pot ser too much

2022-10-06 07:18 UTC, AgustinMJ commented on src/locale/locales/es/common.json
> +    "copy": "Copia",
Copiar potser millor, no?

2022-10-06 07:18 UTC, AgustinMJ commented on test/unit/src/module/transaction/component/display/ReceiveModal/ReceiveModal.spec.tsx
Ojo que ja existia un ReceiveModal.spec.tsx (a module/transaction/component/core). Has canviat el ReceiveCard.spec per ReceiveModal.spec, s'hauria de borrar el ReceiveCard.spec i aplicar aquests canvis en el ReceiveModal.spec que ja existia 👍🏻

2022-10-06 16:46 UTC, GuillemGarciaDev commented on src/module/transaction/component/core/ReceiveModal/ReceiveModal.tsx
> +const TextAddress = styled(Typography, { textTransform: "uppercase" })(() => ({
True no calía el `width: "100%"`. Com només té el `textTransform: "uppercase"` casi que es pot posar com un Typography in-line style no?

2022-10-06 16:48 UTC, GuillemGarciaDev commented on src/module/transaction/component/display/QRCode/QRCode.tsx
> +        <Row justifyContent="center" testID="QRCode" style={{ marginTop: 25 }}>
Oído 🫡. Provo millor amb el gap.

2022-10-06 16:51 UTC, GuillemGarciaDev commented on src/module/common/component/display/Container/Container.types.ts
> +export interface ContainerProps {
Perfecte, per la següent ho tindré en compte. Aniré mirant la docu jeje.

Percert, s'em queixa el linter al ContainerRoot de que fullwidth no te ús... ja t'ho ensenyo demà

2022-10-06 16:54 UTC, GuillemGarciaDev commented on src/locale/locales/es/common.json
> +    "copy": "Copia",
Yes!

2022-10-06 16:56 UTC, GuillemGarciaDev commented on src/module/common/component/display/Container/Container.tsx
> +const Container = (props: ContainerProps) => {
Perfecte!
Té més sentit, es més llegible

2022-10-06 17:03 UTC, GuillemGarciaDev commented on src/module/transaction/component/core/ReceiveModal/ReceiveModal.tsx
> +                <Typography textAlign="center" variant="body2">
Perfecte, ara ja sé on consultar-ho 👌

2022-10-07 06:20 UTC, AgustinMJ commented on src/module/common/component/display/Container/Container.types.ts
> +export interface ContainerProps {
Era perquè no l'estaves utilitzant, estaves fent això:
````jsx
const Container = ({fullWidth, ...rest}):JSX.Element => <Container fullWidth {...rest} />
````
Aquí no uses el fullWidth de les props, ja que posar una prop booleana sense = a algo, aquesta és true, és a dir:
````jsx
<Container fullWidth /> = <Container fullWidth={true} />
````
Per utilitzar el valor hauries de fer
````jsx
<Container fullWidth={fullWidth} />
````
De totes maneres ja veuràs que podies fer això:
````jsx
const Container = (props):JSX.Element => <Container {...props} />
````
O fins i tot exportar directament ConainerRoot, ja que és el mateix component:
````jsx
export default ContainerRoot;
````

2022-10-07 06:23 UTC, AgustinMJ commented on src/module/common/component/display/Container/Container.types.ts
> +    fullWidth?: boolean;
L'he tret perquè no feia falta👍🏻

2022-10-07 06:39 UTC, AgustinMJ commented on src/module/transaction/component/core/ReceiveModal/ReceiveModal.tsx
> +const TextAddress = styled(Typography, { textTransform: "uppercase" })(() => ({
La typography te una prop de textTransform que queda més net :)

A part, he fet un pettit canvi del color, ja que utilitza el overlay[60%]. He utilitzat una Typography extended que hem fet dins del projecte la qual accepta una prop de color. Aquesta prop la hem d'integrar a la llibreria però no ho fem encara perquè vull buscar una manera modular de fer-ho, ja que hi ha molts més components que es beneficiarien d'una prop així

2022-10-07 06:41 UTC, AgustinMJ commented on src/module/transaction/component/display/QRCode/QRCode.tsx
> +        <Row justifyContent="center" testID="QRCode" style={{ marginTop: 25 }}>
He fet un petit canvi del QRCode afegint-li un padding, amb borderRadius i el background blanc, ja que així s'adapta més als dissenys i es veurà bé en el dark mode👍🏻

2022-10-07 06:45 UTC, GuillemGarciaDev commented on src/module/transaction/component/display/QRCode/QRCode.tsx
> +        <Row justifyContent="center" testID="QRCode" style={{ marginTop: 25 }}>
Okey, no el toco aleshores a la meva branch

2022-10-07 07:04 UTC, AgustinMJ approved these changes

2022-10-07 07:11 UTC, merged