RedesignUI: News List
Peersyst/near-mobile-wallet pull request #89
Opened 2022-10-10 07:27 UTC by GuillemGarciaDev

# RedesignUI: News List

## Issue

closes #11 

##Changes

- formatDate + tests
- SimpleNewsCard + styles
- NewsList
- darkTheme + lightTheme
- BigNewsCard
- TransactionDetailsCard
- TransactionDetailsHeader
- es.common.js
- en.common.js

2022-10-10 11:34 UTC, AgustinMJ requested changes

2022-10-10 11:34 UTC, AgustinMJ commented on src/module/news/component/display/SimpleNewsCard/SimpleNewsCard.styles.ts
> +    height: dimensions.width * 0.4,
Què tal si la posem una mica més petita d'altura? Crec que als dissenys és una mica més petit🤔

2022-10-10 11:34 UTC, AgustinMJ commented on src/module/news/component/display/SimpleNewsCard/SimpleNewsCard.tsx
> +                <Col gap={"5%"} justifyContent="center">
Podem posar els gaps dels dissenys més o menys (12 i 2 o així). Els percentatges els feiem servir a ckbull en alguns llocs per fer-ho més responsiu en mòbils petits, però crec que aquí no feia falta, no es nota tant jeje

2022-10-10 11:34 UTC, AgustinMJ commented on src/module/news/screen/NewsScreen.styles.ts
>      paddingHorizontal: 16,
Aquest padding crec que és de 20

2022-10-10 15:39 UTC, GuillemGarciaDev commented on src/module/news/component/display/SimpleNewsCard/SimpleNewsCard.styles.ts
> +    // minHeight: 120,
Ups sorry se m'ha colat

2022-10-10 15:44 UTC, GuillemGarciaDev commented on src/module/news/component/display/SimpleNewsCard/SimpleNewsCard.styles.ts
>      backgroundColor: theme.palette.lightGray,
Ou fck, okey li poso algún semblant dels que no s'eliminin (p.e. gray[100])

2022-10-10 15:45 UTC, GuillemGarciaDev commented on src/module/news/component/display/SimpleNewsCard/SimpleNewsCard.styles.ts
>      backgroundColor: theme.palette.lightGray,
O vols que s'actualitzi el valor?

2022-10-10 15:46 UTC, GuillemGarciaDev commented on src/locale/locales/en/common.json
> +    "idiom": "en",
🫡

2022-10-10 15:58 UTC, GuillemGarciaDev commented on src/module/news/screen/NewsScreen.styles.ts
>      paddingHorizontal: 16,
✅

2022-10-11 10:38 UTC, AgustinMJ approved these changes

2022-10-11 15:30 UTC, merged